import { Lesson } from './types';

export const CURRICULUM: Lesson[] = [
  // ==========================================
  // LEVEL 1: NHẬP MÔN & QUY TẮC CƠ BẢN
  // ==========================================
  {
    id: 'l1-01-ban-co',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Bàn cờ, Cửu Cung & Sông',
    summary: 'Làm quen với lưới 9 cột 10 hàng, khu vực Cung Cấm và ranh giới Sông.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Cấu tạo bàn cờ',
        text: 'Bàn cờ tướng gồm 9 đường dọc và 10 đường ngang với 90 điểm giao cắt. Ở giữa là Sông (Sở Hà - Hán Giới) ngăn đôi hai bên. Mỗi bên có một Cửu Cung 3×3 có hai đường chéo.',
        fen: '9/9/9/9/9/9/9/9/9/9 w - - 0 1',
        highlights: ['d1', 'e1', 'f1', 'd2', 'e2', 'f2', 'd3', 'e3', 'f3'],
      },
      {
        id: 's2',
        type: 'quiz',
        title: 'Kiểm tra nhận biết',
        questions: [
          {
            question: 'Cửu cung gồm bao nhiêu điểm giao cắt?',
            options: ['4 điểm (2 × 2)', '9 điểm (3 × 3)', '16 điểm (4 × 4)', 'Toàn bộ bàn cờ'],
            correctIndex: 1,
            explanation: 'Cửu cung gồm 9 điểm giao cắt (3 hàng × 3 cột) nằm ở giữa phía đáy mỗi bên sân.',
          },
          {
            question: 'Sông nằm giữa các hàng nào trên bàn cờ?',
            options: ['Hàng 1 và 2', 'Hàng 4 và 5', 'Hàng 5 và 6', 'Hàng 9 và 10'],
            correctIndex: 2,
            explanation: 'Sông (Sở Hà - Hán Giới) nằm ngăn cách giữa hàng 5 và hàng 6.',
          },
        ],
      },
    ],
  },
  {
    id: 'l1-02-tuong-si',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Tướng và Sĩ - Trái tim Cửu Cung',
    summary: 'Cách di chuyển và phòng ngự của Tướng và Sĩ trong Cửu Cung.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Quy tắc Tướng và Sĩ',
        text: 'Tướng đi ngang hoặc dọc từng ô một trong Cung. Sĩ đi chéo một ô theo đường kẻ trong Cung. Cả Tướng và Sĩ không bao giờ được rời khỏi Cửu Cung!',
        fen: '3k5/9/9/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['e1', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Di chuyển Tướng',
        text: 'Hãy đi một nước cờ hợp lệ cho Tướng Đỏ!',
        fen: '3k5/9/9/9/9/9/9/9/9/4K4 w - - 0 1',
        goal: 'Đi Tướng lên hoặc sang ngang trong Cung',
        expectedMoves: [
          { from: 'e1', to: 'e2' },
          { from: 'e1', to: 'f1' },
        ],
        wrongMoves: {
          e1d1: 'Tướng không được di chuyển vào cùng cột đối mặt trực tiếp với Tướng đối phương!',
          e1d2: 'Tướng không được đi chéo!',
        },
        hints: ['Tướng chỉ đi 1 ô ngang hoặc dọc trong Cung.'],
      },
      {
        id: 's3',
        type: 'try',
        title: 'Tự làm: Di chuyển Sĩ',
        text: 'Hãy đi Sĩ Đỏ vào tâm Cung e2!',
        fen: '3k5/9/9/9/9/9/9/9/9/3A1K3 w - - 0 1',
        goal: 'Sĩ tiến vào tâm cung e2',
        expectedMoves: [{ from: 'd1', to: 'e2' }],
        hints: ['Sĩ đi chéo 1 ô theo đường chéo trong Cung.'],
      },
    ],
  },
  {
    id: 'l1-03-tuong-ma',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Tượng & Mã - Mắt Tượng & Chân Mã',
    summary: 'Nắm vững quy tắc đi chéo của Tượng, nhảy chữ L của Mã và các điểm cản.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Tượng không qua sông & Cản mắt Tượng',
        text: 'Tượng đi chéo 2 ô (hình vuông 2×2), không bao giờ qua sông. Nếu ô ở giữa đường chéo có quân chắn (gọi là Mắt Tượng), Tượng sẽ bị cản không đi được.',
        fen: '3k5/9/9/9/9/9/9/9/9/2B1K1B2 w - - 0 1',
        highlights: ['c1', 'a3', 'e3'],
      },
      {
        id: 's2',
        type: 'explain',
        title: 'Mã đi chữ L & Cản chân Mã',
        text: 'Mã đi 1 ô thẳng rồi 1 ô chéo (hình chữ L). Nếu ô thẳng kề bên có quân cản (gọi là Chân Mã), Mã sẽ bị cản không nhảy được theo hướng đó.',
        fen: '3k5/9/9/9/9/9/9/9/9/1N2K4 w - - 0 1',
        highlights: ['b1', 'a3', 'c3'],
      },
      {
        id: 's3',
        type: 'try',
        title: 'Tự làm: Nhảy Mã lên c3',
        text: 'Mã Đỏ tại b1 muốn tiến sang ô c3. Hãy thực hiện nước đi!',
        fen: '3k5/9/9/9/9/9/9/9/9/1N2K4 w - - 0 1',
        goal: 'Nhảy Mã lên c3',
        expectedMoves: [{ from: 'b1', to: 'c3' }],
        hints: ['Mã đi 1 bước thẳng lên b2 rồi rẽ chéo sang c3.'],
      },
    ],
  },
  {
    id: 'l1-04-xe-phao',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Xe & Pháo - Sức mạnh tầm xa',
    summary: 'Quy tắc di chuyển không giới hạn của Xe và nguyên lý ngòi Pháo.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Xe đi thẳng - Pháo cần ngòi',
        text: 'Xe đi và ăn quân tự do theo đường ngang và dọc nếu không bị cản. Pháo di chuyển bình thường như Xe, nhưng khi ăn quân BẮT BUỘC phải nhảy qua đúng một quân bất kỳ (gọi là Ngòi).',
        fen: '3k5/9/9/9/9/9/9/9/1C7/R3K4 w - - 0 1',
        highlights: ['a1', 'b2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Dùng Pháo ăn quân qua ngòi',
        text: 'Hãy dùng Pháo Đỏ b1 nhảy qua Tốt b8 để ăn Xe Đen tại b10!',
        fen: '1r1k5/9/1p7/9/9/9/9/9/9/1C2K4 w - - 0 1',
        goal: 'Pháo b1 nhảy qua Tốt b8 ăn Xe b10',
        expectedMoves: [{ from: 'b1', to: 'b10' }],
        hints: ['Pháo có thể ăn quân khi có đúng 1 quân đứng giữa làm ngòi.'],
      },
    ],
  },
  {
    id: 'l1-05-tot-qua-song',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Tốt & Binh - Sức mạnh khi qua sông',
    summary: 'Quy tắc chỉ tiến không lùi và khả năng đi ngang sau khi vượt sông.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Tốt trước và sau khi qua sông',
        text: 'Trước khi qua sông, Tốt chỉ được tiến thẳng từng ô một. Sau khi qua sông, Tốt có thể tiến hoặc đi ngang sang trái/phải 1 ô. Tốt không bao giờ được đi lùi!',
        fen: '3k5/9/9/4p4/9/4P4/9/9/9/4K4 w - - 0 1',
        highlights: ['e5'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Tốt qua sông sang ngang',
        text: 'Tốt Đỏ đã qua sông tại e6. Hãy di chuyển Tốt sang ô d6 hoặc f6!',
        fen: '3k5/9/9/9/4P4/9/9/9/9/4K4 w - - 0 1',
        goal: 'Đi Tốt sang d6 hoặc f6 hoặc tiến lên e7',
        expectedMoves: [
          { from: 'e6', to: 'd6' },
          { from: 'e6', to: 'f6' },
          { from: 'e6', to: 'e7' },
        ],
        hints: ['Tốt đã qua sông có thể đi ngang 1 ô hoặc tiến 1 ô.'],
      },
    ],
  },
  {
    id: 'l1-06-chieu-chieu-bi',
    level: 1,
    levelTitle: 'Cấp 1: Nhập môn',
    title: 'Chiếu Tướng, Chiếu Bí & Hết Nước Đi',
    summary: 'Phân biệt đòn Chiếu, cách Hóa giải và tình huống Xử thua khi hết nước đi.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Quy tắc thoát chiếu',
        text: 'Khi bị Chiếu, người chơi phải ngay lập tức: 1. Ăn quân đang chiếu; 2. Dùng quân khác che chắn; hoặc 3. Chạy Tướng. Nếu không thể làm cách nào thì bị Chiếu Bí (Thua cuộc).',
        fen: '4k4/9/9/9/9/9/9/9/9/R3K4 w - - 0 1',
        highlights: ['a1', 'e10'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đưa Xe lên chiếu bí',
        text: 'Tướng Đen bị kẹt ở góc. Hãy đưa Xe Đỏ lên hàng đáy a10 để chiếu bí!',
        fen: '3k5/9/9/9/9/9/9/9/R8/4K4 w - - 0 1',
        goal: 'Đưa Xe a2 lên a10 chiếu bí',
        expectedMoves: [{ from: 'a2', to: 'a10' }],
        hints: ['Xe di chuyển thẳng đứng một mạch lên hàng đáy.'],
      },
    ],
  },

  // ==========================================
  // LEVEL 2: KHAI CUỘC KINH ĐIỂN (OPENINGS MASTERCLASS)
  // ==========================================
  {
    id: 'l2-01-nguyen-ly-khai-cuoc',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Nguyên Lý Vàng Trong Khai Cuộc',
    summary: '3 nguyên lý sống còn: Xuất quân nhanh, kiểm soát trung lộ và phối hợp binh chủng.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Ba nguyên tắc cơ bản',
        text: '1. Xuất Xe nhanh (thông thoáng lộ Xe trong 3 nước đầu).\n2. Tránh đi 1 quân nhiều lần trong khai cuộc.\n3. Mã giữ trung lộ, Pháo yểm trợ và Tốt mở đường.',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nước mở đầu chuẩn mực (P2-5)',
        text: 'Hãy vào Pháo trung lộ để chiếm tiên thế tấn công vào trung tâm!',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
        goal: 'Vào Pháo 2 bình 5 (h3 -> e3)',
        expectedMoves: [{ from: 'h3', to: 'e3' }],
        hints: ['Di chuyển Pháo bên cánh phải vào ô e3 giữa bàn cờ.'],
      },
    ],
  },
  {
    id: 'l2-02-phao-dau-trung-phao',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Pháo Đầu (Trung Pháo) - Công Thủ Toàn Diện',
    summary: 'Thế trận tấn công trực diện vào Tốt đầu và tâm cung của đối phương.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Sức mạnh của Pháo Đầu',
        text: 'Pháo Đầu kiểm soát cột 5 (trung lộ), khóa chặt Tướng đối phương và gây áp lực liên tục lên Tốt đầu. Đối phương buộc phải tìm cách phòng thủ hoặc đối công.',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/4C1C2/9/RNBAKABNR b - - 0 1',
        highlights: ['e3', 'e7', 'e10'],
      },
      {
        id: 's2',
        type: 'quiz',
        title: 'Trắc nghiệm chiến thuật',
        questions: [
          {
            question: 'Mục tiêu tấn công trực tiếp của Pháo Đầu là gì?',
            options: ['Tốt đầu (cột 5) và Trung lộ đối phương', 'Tượng biên', 'Sĩ đáy', 'Không có mục tiêu cố định'],
            correctIndex: 0,
            explanation: 'Pháo Đầu nhắm thẳng vào Tốt 5 và cột trung lộ, kiểm soát đường tâm của đối phương.',
          },
        ],
      },
    ],
  },
  {
    id: 'l2-03-binh-phong-ma',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Bình Phong Mã - Bức Tường Thép',
    summary: 'Thế trận phòng ngự phản công hoàn hảo nhất đối phó với Pháo Đầu.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Cấu trúc hai Mã giữ nhau',
        text: 'Bình Phong Mã là thế trận đưa cả 2 Mã lên c7 và g7 bảo vệ Tốt đầu (e7). Hai Mã như bức bình phong vững chắc, liên kết chặt chẽ với Sĩ Tượng.',
        fen: 'r1bakab1r/9/1cn2n1c1/p1p1p1p1p/9/9/P1P1P1P1P/4C1C2/9/RNBAKABNR w - - 0 1',
        highlights: ['c8', 'g8', 'e7'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nhảy Mã lên c3 giữ Tốt đầu',
        text: 'Hãy đưa Mã b1 nhảy lên c3 để giữ vững trung tâm!',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/4C1C2/9/RNBAKABNR w - - 0 1',
        goal: 'Nhảy Mã b1 lên c3 (M8.7)',
        expectedMoves: [{ from: 'b1', to: 'c3' }],
        hints: ['Mã b1 nhảy lên c3.'],
      },
    ],
  },
  {
    id: 'l2-04-thuan-phao',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Thuận Pháo - Đôi Công Nảy Lửa',
    summary: 'Khi cả hai bên cùng vào Pháo cùng một hướng để quyết đấu.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Khái niệm Thuận Pháo',
        text: 'Khi Đỏ đi Pháo 2 bình 5, Đen cũng đi Pháo 8 bình 5 (cùng hướng). Cả hai bên đều chọn lối đánh tấn công cởi mở, thế trận diễn ra vô cùng quyết liệt và nhanh chóng.',
        fen: 'rnbakab1r/9/1c4c2/p1p1p1p1p/9/9/P1P1P1P1P/4C1C1N/9/RNBAKAB1R w - - 0 1',
        highlights: ['e3', 'e8'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xuất Xe cánh phải',
        text: 'Trong thế Thuận Pháo, sau khi Mã đã nhảy giữ chốt thì xuất Xe ngay. Hãy đưa Xe i1 sang h1!',
        fen: 'rnbakab1r/9/1c4c2/p1p1p1p1p/9/9/P1P1P1P1P/4C1C1N/9/RNBAKAB1R w - - 0 1',
        goal: 'Xe i1 bình h1 (X9-8)',
        expectedMoves: [{ from: 'i1', to: 'h1' }],
        hints: ['Xe di chuyển ngang sang ô h1.'],
      },
    ],
  },
  {
    id: 'l2-05-nghich-phao',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Nghịch Pháo (Liệt Thủ Pháo) - Can Qua Đối Đầu',
    summary: 'Hai bên vào Pháo ngược hướng nhau, tạo thế trận tương kế tựu kế.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Khái niệm Nghịch Pháo',
        text: 'Đỏ đi Pháo 2 bình 5 (bên phải vào giữa), Đen đi Pháo 2 bình 5 (bên trái vào giữa). Cả 2 cùng nhắm vào cánh yếu của đối phương, tạo nên thế trận không khoan nhượng.',
        fen: 'rnbakabnr/9/2c3c2/p1p1p1p1p/9/9/P1P1P1P1P/4C1C2/9/RNBAKABNR w - - 0 1',
        highlights: ['e3', 'e8'],
      },
      {
        id: 's2',
        type: 'quiz',
        title: 'Đặc trưng Nghịch Pháo',
        questions: [
          {
            question: 'Điểm đặc trưng nhất của trận Nghịch Pháo là gì?',
            options: ['Công thủ toàn diện, trận đấu hòa nhiều', 'Hai bên tấn công vào cánh đối nghịch của nhau', 'Không bao giờ xuất Xe', 'Chỉ dùng Tốt qua sông'],
            correctIndex: 1,
            explanation: 'Nghịch Pháo đưa hai Pháo vào ngược hướng, khiến cánh công của bên này đánh thẳng vào cánh hở của bên kia.',
          },
        ],
      },
    ],
  },
  {
    id: 'l2-06-tien-nhan-chi-lo',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Tiên Nhân Chỉ Lộ (Binh 7 Tiến 1)',
    summary: 'Nước cờ ném đá dò đường thông minh, linh hoạt chuyển biến thế trận.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Ý nghĩa nước Binh 7 tiến 1',
        text: 'Nước đi mở Tốt 7 (hoặc Tốt 3) giúp thông đường cho Mã nhảy lên, vừa thăm dò phản ứng của đối phương (vào Pháo, đè Tốt hay bay Tượng).',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/2P6/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
        highlights: ['c5'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đi nước Tiên Nhân Chỉ Lộ',
        text: 'Hãy tiến Tốt c4 lên c5 để mở màn thế trận Tiên Nhân Chỉ Lộ!',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
        goal: 'Binh 7 tiến 1 (c4 -> c5)',
        expectedMoves: [{ from: 'c4', to: 'c5' }],
        hints: ['Tiến Tốt tại cột c một ô lên phía trước.'],
      },
    ],
  },
  {
    id: 'l2-07-phi-tuong-cuoc',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Phi Tượng Cuộc - Vững Như Bàn Thạch',
    summary: 'Lối chơi củng cố phòng ngự từ nước đầu tiên, chuyển từ thủ sang công vững vàng.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Triết lý Phi Tượng',
        text: 'Nước Tượng 3 tiến 5 hoặc Tượng 7 tiến 5 củng cố chắc chắn trung tâm bàn cờ, bảo vệ Tốt đầu và sẵn sàng đối phó với mọi thế công nhanh của đối phương.',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/4B4/RNBAKA1NR w - - 0 1',
        highlights: ['e3'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Bay Tượng lên tâm e3',
        text: 'Hãy đưa Tượng g1 bay lên e3 để hoàn thiện nước Phi Tượng!',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
        goal: 'Tượng g1 tiến e3 (T7.5)',
        expectedMoves: [{ from: 'g1', to: 'e3' }],
        hints: ['Tượng đi chéo 2 ô lên tâm cung e3.'],
      },
    ],
  },
  {
    id: 'l2-08-si-giac-qua-cung-phao',
    level: 2,
    levelTitle: 'Cấp 2: Khai cuộc',
    title: 'Sĩ Giác Pháo & Quá Cung Pháo',
    summary: 'Đòn đánh Pháo linh hoạt ở góc Sĩ và ngang qua Cung nhắm vào cánh đối phương.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Đặc trưng Pháo Quá Cung & Sĩ Giác',
        text: 'Quá Cung Pháo (Pháo 2 bình 6) tập trung hỏa lực sang một cánh. Sĩ Giác Pháo (Pháo 2 thoái 1 hoặc chuyển sang d3) kiểm soát đường sườn và trợ công cho Mã.',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/3C3C1/9/RNBAKABNR w - - 0 1',
        highlights: ['d3'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Bình Pháo Quá Cung (h3 sang d3)',
        text: 'Hãy đưa Pháo h3 sang d3 để triển khai thế trận Quá Cung Pháo!',
        fen: 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1',
        goal: 'Pháo h3 bình d3 (P2-6)',
        expectedMoves: [{ from: 'h3', to: 'd3' }],
        hints: ['Di chuyển Pháo ngang qua cung sang ô d3.'],
      },
    ],
  },

  // ==========================================
  // LEVEL 3: 36 SÁT PHÁP KINH ĐIỂN (CHECKMATING TACTICS)
  // ==========================================
  {
    id: 'l3-01-ma-hau-phao',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 1: Mã Hậu Pháo',
    summary: 'Đòn sát thủ kinh điển: Mã phía trước khống chế lối thoát, Pháo sau lưng chiếu bí.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Cơ chế Mã Hậu Pháo',
        text: 'Mã đứng trước cách Tướng 1 ô để khóa đường di chuyển của Tướng, đồng thời làm ngòi cho Pháo đứng ngay sau lưng chiếu thẳng vào mặt Tướng.',
        fen: '4k4/4N4/4C4/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['e9', 'e8', 'e10'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Mã Hậu Pháo kết liễu',
        text: 'Mã Đỏ đã đứng ở ô d9. Hãy đưa Pháo c8 sang d8 để hoàn tất thế Mã Hậu Pháo!',
        fen: '3ak4/3N5/2C6/9/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Pháo c8 bình d8 chiếu bí',
        expectedMoves: [{ from: 'c8', to: 'd8' }],
        hints: ['Đưa Pháo sang đứng sau lưng Mã tại d8.'],
      },
    ],
  },
  {
    id: 'l3-02-thiet-mon-han',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 2: Thiết Môn Hãn (Cửa Sắt)',
    summary: 'Dùng Pháo ép trung lộ làm khóa, Xe xộc thẳng vào hàng đáy kết liễu.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý Thiết Môn Hãn',
        text: 'Pháo Đỏ giữ chặt cột 5 (trung lộ) khóa Tướng không cho sang ngang. Xe hoặc Tốt xộc thẳng vào mặt Sĩ hoặc đáy cung để tạo thế Cửa Sắt không thể phá.',
        fen: '3ak4/4a4/4C4/9/9/9/9/9/8R/4K4 w - - 0 1',
        highlights: ['e8', 'i2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe cắm đáy chiếu Thiết Môn Hãn',
        text: 'Pháo trung lộ đã ghim chặt cung. Hãy đưa Xe i2 lên i10 chiếu bí!',
        fen: '3ak4/4a4/4C4/9/9/9/9/9/8R/4K4 w - - 0 1',
        goal: 'Xe i2 tiến i10 (X9.8)',
        expectedMoves: [{ from: 'i2', to: 'i10' }],
        hints: ['Đưa Xe phi thẳng lên hàng 10 của đối phương.'],
      },
    ],
  },
  {
    id: 'l3-03-trac-dien-ho',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 3: Trắc Diện Hổ (Hổ Vồ Sườn)',
    summary: 'Mã khống chế góc Cung và Sĩ, Xe đâm ngang sườn chiếu bí.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý Trắc Diện Hổ',
        text: 'Mã đứng ở góc Cung (như c8 hoặc g8) bịt đường thoát của Tướng, Xe đâm thẳng vào sườn (cột 4 hoặc 6) như mãnh hổ vồ mồi.',
        fen: '3k5/3a5/2N6/9/9/9/9/9/8R/4K4 w - - 0 1',
        highlights: ['c8', 'i2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đưa Xe lên hàng đáy chiếu bí',
        text: 'Mã c8 đã khóa chặt Tướng. Hãy đưa Xe i2 lên i10 chiếu bí!',
        fen: '3k5/3a5/2N6/9/9/9/9/9/8R/4K4 w - - 0 1',
        goal: 'Xe i2 tiến i10 (X9.8)',
        expectedMoves: [{ from: 'i2', to: 'i10' }],
        hints: ['Đưa Xe phi thẳng lên hàng 10.'],
      },
    ],
  },
  {
    id: 'l3-04-song-ma-am-tuyen',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 4: Song Mã Ẩm Tuyền (Ngựa Uống Suối)',
    summary: 'Hai Mã liên hoàn nhảy vào Cung tương trợ nhau chiếu bí.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Sức mạnh hai Mã liên hoàn',
        text: 'Hai Mã phối hợp: một Mã nhảy vào góc Cung chiếu ép Tướng lên tầng 2 hoặc ra góc, Mã kia lập tức nhảy tiếp vào điểm hiểm chiếu bí đối phương.',
        fen: '3k5/9/3N1N3/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['d8', 'f8'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nhảy Mã kết liễu',
        text: 'Tướng Đen tại e10. Hãy nhảy Mã d8 lên c10 chiếu bí!',
        fen: '4k4/9/3N1N3/9/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Mã d8 nhảy lên c10 hoặc f8 lên g10',
        expectedMoves: [{ from: 'd8', to: 'c10' }, { from: 'f8', to: 'g10' }],
        hints: ['Nhảy 1 trong 2 Mã lên góc hàng đáy c10 hoặc g10.'],
      },
    ],
  },
  {
    id: 'l3-05-hai-day-mo-trang',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 5: Hải Đáy Mò Trăng (Mò Trăng Đáy Biển)',
    summary: 'Dùng Xe hoặc Pháo luồn xuống đáy Cung đối phương mượn bóng Tướng kết liễu.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Đặc trưng Hải Đáy Mò Trăng',
        text: 'Thường xuất hiện trong tàn cuộc Xe Pháo đối Xe Sĩ: Xe Đỏ ghìm giữ Tướng và Sĩ ở trên, Pháo luồn xuống tận hàng đáy (hàng 10) mượn Xe làm ngòi bắn chết Tướng.',
        fen: '4k4/4a4/9/9/9/9/9/9/4C4/3RK4 w - - 0 1',
        highlights: ['d1', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đưa Xe đè đáy',
        text: 'Hãy đưa Xe d1 lên d10 chiếu ép Tướng!',
        fen: '4k4/4a4/9/9/9/9/9/9/4C4/3RK4 w - - 0 1',
        goal: 'Xe d1 tiến d10 (X4.9)',
        expectedMoves: [{ from: 'd1', to: 'd10' }],
        hints: ['Phi Xe một mạch lên hàng 10.'],
      },
    ],
  },
  {
    id: 'l3-06-dai-dao-khoan-tram',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 6: Đại Đao Khoan Trảm (Chém Sĩ)',
    summary: 'Xe phối hợp cùng Tốt hoặc Mã dũng mãnh chém thẳng vào Sĩ tâm để kết liễu.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Cơ chế Đại Đao Khoan Trảm',
        text: 'Khi có Tốt hoặc Pháo trợ lực ở trung tâm, Xe không ngần ngại phế vào Sĩ tâm (e9 hoặc e10) phá tan toàn bộ hệ thống phòng thủ của đối phương.',
        fen: '3ak4/4a4/3P5/9/9/9/9/9/4R4/4K4 w - - 0 1',
        highlights: ['d8', 'e9'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe chém Sĩ chiếu bí',
        text: 'Tốt d8 giữ ô e9. Hãy đưa Xe e2 chém thẳng Sĩ e9 chiếu bí!',
        fen: '3ak4/4a4/3P5/9/9/9/9/9/4R4/4K4 w - - 0 1',
        goal: 'Xe e2 chém Sĩ e9 (X5.7)',
        expectedMoves: [{ from: 'e2', to: 'e9' }],
        hints: ['Dùng Xe ăn thẳng quân Sĩ tại ô e9.'],
      },
    ],
  },
  {
    id: 'l3-07-song-tap-phao',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 7: Song Táp Pháo (Pháo Gánh Trùng Điệp)',
    summary: 'Hai Pháo cùng trên một cột hoặc hàng ngang gối đầu nhau bắn phá.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý Song Táp Pháo',
        text: 'Hai Pháo cùng xếp trên 1 cột: Pháo trước làm ngòi cho Pháo sau chiếu, khi đối phương che chắn thì Pháo trước lại nhảy đi chiếu tiếp tạo vòng lặp sát cục.',
        fen: '4k4/9/4C4/4C4/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['e8', 'e7'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đưa Pháo sau chiếu bí',
        text: 'Hãy đưa Pháo e7 tiến lên e9 chiếu bí đối phương!',
        fen: '4k4/4a4/4C4/4C4/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Pháo e7 tiến e9',
        expectedMoves: [{ from: 'e7', to: 'e9' }],
        hints: ['Pháo e7 nhảy qua Pháo e8 ăn vào e9.'],
      },
    ],
  },
  {
    id: 'l3-08-bat-son-cai-the',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 8: Bạt Sơn Cái Thế (Xe Đè Nắp Cung)',
    summary: 'Xe chiếm lĩnh hàng 9 (họng Cung), bịt kín lối lên của Tướng đối phương.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Đặc trưng Bạt Sơn Cái Thế',
        text: 'Xe Đỏ đóng chặt ở hàng 9 như tảng núi đè xuống, Tướng Đen ở hàng 10 không thể ngóc đầu lên và chịu trận trước các đòn công của Mã hoặc Pháo.',
        fen: '4k4/R8/9/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['a9'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe khóa hàng 9',
        text: 'Hãy đưa Xe a1 tiến thẳng lên a9 để khóa chặt nắp Cung!',
        fen: '3ak4/9/9/9/9/9/9/9/4A4/R3K4 w - - 0 1',
        goal: 'Xe a1 tiến a9 (X1.8)',
        expectedMoves: [{ from: 'a1', to: 'a9' }],
        hints: ['Xe phi thẳng lên hàng 9.'],
      },
    ],
  },
  {
    id: 'l3-09-ngoa-long-cuong',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 9: Ngọa Tào Mã (Rồng Nằm Gốc Cung)',
    summary: 'Mã nhảy vào ô Ngọa Tào (c8/g8) chiếu tướng và khống chế toàn bộ Cung.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Vị trí Ngọa Tào hiểm hóc',
        text: 'Ô c8 và g8 (Ngọa Tào) là hai vị trí chiến lược bậc nhất của Mã. Từ đây Mã vừa chiếu Tướng, vừa khóa Tướng sang ngang, mở đường cho Xe Pháo kết liễu.',
        fen: '3k5/9/2N6/9/9/9/9/9/9/4K4 w - - 0 1',
        highlights: ['c8'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nhảy Mã Ngọa Tào chiếu bí',
        text: 'Xe giữ cột 4. Hãy nhảy Mã b6 vào c8 chiếu bí!',
        fen: '3k5/9/9/9/1N7/9/9/9/3R5/4K4 w - - 0 1',
        goal: 'Mã b6 nhảy c8 chiếu bí',
        expectedMoves: [{ from: 'b6', to: 'c8' }],
        hints: ['Mã nhảy chữ L vào ô c8.'],
      },
    ],
  },
  {
    id: 'l3-10-thien-ma-hanh-khong',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 10: Điền Tự Mã (Mã Góc Chiếu Bí)',
    summary: 'Mã nhảy vào các góc xa chiếu ép Tướng không có đường lui.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Mã góc hiểm hóc',
        text: 'Khi Tướng bị dồn lên hàng 2 của Cung, Mã từ xa nhảy vào các góc hiểm chiếu thẳng, khiến Tướng không thể thụt xuống hay sang ngang.',
        fen: '4k4/9/9/3N5/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['d7'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nhảy Mã chiếu bí',
        text: 'Tướng Đen tại d10. Hãy nhảy Mã d7 lên f8 chiếu bí!',
        fen: '3k5/9/9/3N5/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Mã d7 nhảy f8 hoặc c9',
        expectedMoves: [{ from: 'd7', to: 'f8' }, { from: 'd7', to: 'c9' }],
        hints: ['Nhảy Mã lên f8 hoặc c9.'],
      },
    ],
  },
  {
    id: 'l3-11-song-xe-toa-giap',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 11: Song Xe Tỏa Giáp (Hai Xe Kẹp Nách)',
    summary: 'Hai Xe chiếm hai cột kề bên Cửu Cung, thay nhau chiếu dồn Tướng vào đường cùng.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý Song Xe Tỏa Giáp',
        text: 'Hai Xe Đỏ chiếm cột 4 và cột 6 (hoặc cột 5 và 6). Một Xe chiếu ở hàng đáy, buộc Tướng chạy sang cột bên kia thì Xe thứ hai lập tức đâm xuống kết liễu.',
        fen: '3k5/9/9/9/9/9/9/9/3R1R3/4A1K2 w - - 0 1',
        highlights: ['d1', 'f1'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe đâm đáy chiếu bí',
        text: 'Xe d10 đang giữ Tướng. Hãy đưa Xe f2 tiến lên f10 chiếu bí!',
        fen: '3Rk4/9/9/9/9/9/9/9/4AR3/4K4 w - - 0 1',
        goal: 'Xe f2 tiến f10 (X6.8)',
        expectedMoves: [{ from: 'f2', to: 'f10' }],
        hints: ['Đưa Xe f2 phi thẳng lên hàng 10.'],
      },
    ],
  },
  {
    id: 'l3-12-tien-tram-hau-tau',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 12: Tiền Trảm Hậu Tấu (Phế Quân Mở Đường)',
    summary: 'Hy sinh Xe hoặc Pháo để phá tan lớp phòng ngự bảo vệ Tướng.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Ý đồ phế quân',
        text: 'Khi đối phương có hàng phòng thủ Sĩ Tượng dày đặc, ta chủ động hi sinh quân mạnh (như phế Xe ăn Sĩ) để kéo Tướng ra vị trí xấu rồi dùng các quân còn lại chiếu bí tức thì.',
        fen: '3ak4/4a4/9/9/9/9/9/9/4R4/4K4 w - - 0 1',
        highlights: ['e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Phế Xe mở đường',
        text: 'Hãy đưa Xe e2 ăn Sĩ e9 chiếu ép Tướng!',
        fen: '3ak4/4a4/9/9/9/9/9/9/4R4/4K4 w - - 0 1',
        goal: 'Xe e2 ăn Sĩ e9',
        expectedMoves: [{ from: 'e2', to: 'e9' }],
        hints: ['Dùng Xe chém thẳng vào Sĩ tâm e9.'],
      },
    ],
  },
  {
    id: 'l3-13-nhi-quy-phach-mon',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 13: Nhị Quỷ Phách Môn (Song Tốt Vỗ Cửa)',
    summary: 'Hai Tốt qua sông áp sát Cửu Cung như hai quỷ dữ bẻ gãy phòng thủ.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Sức mạnh Song Tốt áp Cung',
        text: 'Hai Tốt Đỏ đã qua sông, chiếm lĩnh hai bên tai Cung (d9 và f9). Lúc này Sĩ không thể cản, Tướng bị khóa chặt và chịu thua trước sức ép của Song Tốt.',
        fen: '3k5/3PP4/9/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['d9', 'e9'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Tốt vỗ mặt chiếu bí',
        text: 'Tướng Đen tại e10. Hãy đưa Tốt e9 tiến lên e10 ăn Tướng!',
        fen: '4k4/3PP4/9/9/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Tốt e9 tiến e10',
        expectedMoves: [{ from: 'e9', to: 'e10' }],
        hints: ['Tiến Tốt e9 lên ô e10.'],
      },
    ],
  },
  {
    id: 'l3-14-giac-dau-phao',
    level: 3,
    levelTitle: 'Cấp 3: Sát pháp',
    title: 'Sát Pháp 14: Giác Đầu Pháo (Pháo Góc Cung)',
    summary: 'Pháo nằm tại góc Cung (cột 4/6 hàng 9/10) phối hợp cùng Xe Tốt chiếu bí.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Cơ chế Giác Đầu Pháo',
        text: 'Pháo Đỏ cắm ở góc Cung (ô d10 hoặc f10), khống chế hoàn toàn đường di chuyển của Tướng và Sĩ, phối hợp với Xe hoặc Mã kết liễu nhanh gọn.',
        fen: '3C1k3/9/9/9/9/9/9/9/4R4/4K4 w - - 0 1',
        highlights: ['d10'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe phối hợp Pháo góc chiếu bí',
        text: 'Pháo d10 đã khóa Tướng. Hãy đưa Xe e2 tiến lên e10 chiếu bí!',
        fen: '3C1k3/9/9/9/9/9/9/9/4R4/4K4 w - - 0 1',
        goal: 'Xe e2 tiến e10 (X5.8)',
        expectedMoves: [{ from: 'e2', to: 'e10' }],
        hints: ['Đưa Xe phi thẳng lên hàng 10.'],
      },
    ],
  },

  // ==========================================
  // LEVEL 4: TÀN CUỘC CĂN BẢN & ĐỊNH THỨC THẮNG - HÒA
  // ==========================================
  {
    id: 'l4-01-don-xe-thang-don-si-tuong',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Đơn Xe Thắng Đơn Sĩ / Đơn Tượng',
    summary: 'Kỹ thuật dùng Đơn Xe bắt lẻ và cô lập Sĩ hoặc Tượng để giành chiến thắng tuyệt đối.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý bắt Sĩ và Tượng',
        text: 'Đơn Xe luôn thắng Đơn Sĩ hoặc Đơn Tượng bằng cách chiếm trung lộ, dùng mặt Tướng trợ lực và ép đối phương vào thế hết nước đi hoặc mất quân.',
        fen: '3ak4/9/9/9/9/9/9/9/8R/4K4 w - - 0 1',
        highlights: ['d10', 'i2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Chiếm trung lộ ép Sĩ',
        text: 'Hãy đưa Xe i2 sang e2 để chiếm cột 5 trung lộ!',
        fen: '3ak4/9/9/9/9/9/9/9/8R/4K4 w - - 0 1',
        goal: 'Xe i2 bình e2 (X9-5)',
        expectedMoves: [{ from: 'i2', to: 'e2' }],
        hints: ['Xe di chuyển ngang sang ô e2.'],
      },
    ],
  },
  {
    id: 'l4-02-don-xe-thang-ma-song-si',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Đơn Xe Thắng Mã Song Sĩ',
    summary: 'Cách dùng Xe chia cắt Mã với Sĩ và đưa Tướng vào thế bất động.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Chiến thuật cô lập Mã',
        text: 'Mã Song Sĩ nếu đứng đúng vị trí có thể thủ hòa, nhưng nếu Mã bị Xe Đỏ ép ra biên hoặc cản chân, Xe sẽ bắt sống Mã và thắng dễ dàng.',
        fen: '3ak4/4a4/2n6/9/9/9/9/9/4R4/4K4 w - - 0 1',
        highlights: ['c8', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Dùng Xe đè Mã',
        text: 'Hãy đưa Xe e2 sang c2 để đè bắt Mã c8!',
        fen: '3ak4/4a4/2n6/9/9/9/9/9/4R4/4K4 w - - 0 1',
        goal: 'Xe e2 bình c2 (X5-3)',
        expectedMoves: [{ from: 'e2', to: 'c2' }],
        hints: ['Xe di chuyển ngang sang ô c2.'],
      },
    ],
  },
  {
    id: 'l4-03-don-xe-thang-phao-song-si',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Đơn Xe Thắng Pháo Song Sĩ',
    summary: 'Tận dụng điểm yếu thiếu ngòi của Pháo để ép đối phương mất quân.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Điểm yếu của Pháo tàn cuộc',
        text: 'Trong tàn cuộc, Pháo không có nhiều quân làm ngòi. Xe Đỏ chiếm trung lộ, ép Tướng Đen lệch sang một bên rồi bắt chết Sĩ hoặc Pháo.',
        fen: '3ak4/4a4/4c4/9/9/9/9/9/4R4/4K4 w - - 0 1',
        highlights: ['e8', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Xe ăn Pháo',
        text: 'Pháo Đen tại e8 không có ngòi che. Hãy đưa Xe e2 ăn thẳng Pháo e8!',
        fen: '3ak4/4a4/4c4/9/9/9/9/9/4R4/4K4 w - - 0 1',
        goal: 'Xe e2 ăn Pháo e8 (X5.6)',
        expectedMoves: [{ from: 'e2', to: 'e8' }],
        hints: ['Dùng Xe tiến lên ăn quân Pháo tại e8.'],
      },
    ],
  },
  {
    id: 'l4-04-phao-tot-thang-si-tuong-toan',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Pháo Tốt Thắng Sĩ Tượng Toàn',
    summary: 'Kỹ thuật dùng Pháo mượn Tướng làm ngòi kết hợp Tốt nhập cung.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Nguyên lý Pháo Tốt khống chế',
        text: 'Pháo giữ trung lộ hoặc đáy cung, Tốt Đỏ từ từ tiến vào chiếm tai Cung (d9/f9), mượn Sĩ đối phương làm ngòi để bắt chết từng quân phòng thủ.',
        fen: '2bakab2/9/4P4/9/9/9/9/9/4C4/4K4 w - - 0 1',
        highlights: ['e8', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Đưa Tốt áp sát Cung',
        text: 'Hãy đưa Tốt e8 tiến lên e9 để uy hiếp Sĩ tâm!',
        fen: '2bakab2/9/4P4/9/9/9/9/9/4C4/4K4 w - - 0 1',
        goal: 'Tốt e8 tiến e9 (B5.1)',
        expectedMoves: [{ from: 'e8', to: 'e9' }],
        hints: ['Tiến Tốt lên ô e9.'],
      },
    ],
  },
  {
    id: 'l4-05-ma-cao-binh-thang-si-tuong-toan',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Mã Cao Binh Thắng Sĩ Tượng Toàn',
    summary: 'Sự kết hợp hoàn hảo giữa bước nhảy linh hoạt của Mã và sức ép của Tốt cao.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Khái niệm Mã Cao Binh',
        text: 'Mã Cao Binh là thế cờ Mã phối hợp cùng Tốt chưa lọt đáy (Tốt ở hàng 7 hoặc 8). Tốt khống chế đường ra của Tướng, Mã nhảy vào các điểm yếu bắt Sĩ.',
        fen: '2bakab2/9/4P4/9/9/9/9/9/4N4/4K4 w - - 0 1',
        highlights: ['e8', 'e2'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Nhảy Mã lên d4 tham chiến',
        text: 'Hãy đưa Mã e2 nhảy lên d4 hoặc f4 để chuẩn bị thâm nhập Cung!',
        fen: '2bakab2/9/4P4/9/9/9/9/9/4N4/4K4 w - - 0 1',
        goal: 'Mã e2 nhảy d4 (M5.6)',
        expectedMoves: [{ from: 'e2', to: 'd4' }, { from: 'e2', to: 'f4' }],
        hints: ['Mã nhảy lên d4 hoặc f4.'],
      },
    ],
  },
  {
    id: 'l4-06-song-tot-thang-si-tuong-toan',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Song Tốt Thắng Sĩ Tượng Toàn',
    summary: 'Hai Tốt qua sông liên hoàn bẻ gãy hệ thống phòng ngự trọn vẹn.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Sức mạnh Song Tốt liên kết',
        text: 'Hai Tốt đi liền nhau như hai dũng sĩ bảo vệ nhau, từ từ áp sát Cửu Cung, khống chế các vị trí trọng yếu và ép Tướng đối phương vào thế bí.',
        fen: '2bakab2/9/3PP4/9/9/9/9/9/4A4/4K4 w - - 0 1',
        highlights: ['d8', 'e8'],
      },
      {
        id: 's2',
        type: 'try',
        title: 'Tự làm: Tiến Tốt chiếm tai Cung',
        text: 'Hãy đưa Tốt d8 tiến lên d9 để khống chế tai Cung!',
        fen: '2bakab2/9/3PP4/9/9/9/9/9/4A4/4K4 w - - 0 1',
        goal: 'Tốt d8 tiến d9 (B4.1)',
        expectedMoves: [{ from: 'd8', to: 'd9' }],
        hints: ['Tiến Tốt d8 lên 1 ô.'],
      },
    ],
  },
  {
    id: 'l4-07-don-khuyet-tuong-ky-phao',
    level: 4,
    levelTitle: 'Cấp 4: Tàn cuộc',
    title: 'Đơn Khuyết Tượng Kỵ Pháo (Khuyết Tượng Sợ Pháo)',
    summary: 'Khẩu quyết tàn cuộc kinh điển: Mất Tượng sợ Pháo, Mất Sĩ sợ Xe.',
    steps: [
      {
        id: 's1',
        type: 'explain',
        title: 'Khẩu quyết tàn cuộc',
        text: 'Khi phòng ngự tàn cuộc:\n- "Khuyết Tượng kỵ Pháo": Mất Tượng sẽ tạo điều kiện cho Pháo đối phương mượn ngòi tấn công.\n- "Khuyết Sĩ kỵ Xe": Mất Sĩ sẽ tạo kẽ hở cho Xe đối phương đâm sườn chiếu bí.',
        fen: '3akab2/9/9/9/9/9/9/9/4C4/4K4 w - - 0 1',
      },
      {
        id: 's2',
        type: 'quiz',
        title: 'Trắc nghiệm khẩu quyết',
        questions: [
          {
            question: 'Trong tàn cuộc cờ tướng, câu khẩu quyết nào sau đây là chính xác?',
            options: [
              'Khuyết Tượng kỵ Pháo, Khuyết Sĩ kỵ Xe',
              'Khuyết Tượng kỵ Xe, Khuyết Sĩ kỵ Pháo',
              'Khuyết Tốt kỵ Mã, Khuyết Sĩ kỵ Tốt',
              'Có Tượng sợ Xe, Có Sĩ sợ Mã',
            ],
            correctIndex: 0,
            explanation: 'Khẩu quyết chuẩn là: "Khuyết Tượng kỵ Pháo, Khuyết Sĩ kỵ Xe".',
          },
        ],
      },
    ],
  },
];
