import { OpeningCategory, OpeningVariation } from './openingTypes';

export const OPENING_CATEGORIES: { id: OpeningCategory; name: string; icon: string; count: number; description: string }[] = [
  {
    id: 'trung-phao',
    name: 'Trung Pháo (Pháo Đầu)',
    icon: '💣',
    count: 6,
    description: 'Trận hình công kích mãnh liệt nhất trong Cờ Tướng, kiểm soát trung lộ và uy hiếp trung lộ đối phương.',
  },
  {
    id: 'binh-phong-ma',
    name: 'Bình Phong Mã',
    icon: '🛡️',
    count: 5,
    description: 'Trận pháp phòng thủ phản công kinh điển số 1, hai Mã trấn giữ trung lộ vững chắc như bức bình phong bằng đồng.',
  },
  {
    id: 'nghich-phao',
    name: 'Nghịch Pháo (Liệt Thủ Pháo)',
    icon: '⚔️',
    count: 3,
    description: 'Trận địa đối công nảy lửa một mất một còn, hai bên cùng vào Pháo đầu nghịch cánh quyết đấu sinh tử.',
  },
  {
    id: 'phan-cung-ma',
    name: 'Phản Cung Mã (Giáp Pháo Xuyên Cung)',
    icon: '🏹',
    count: 3,
    description: 'Trận hình uyển chuyển biến ảo, một Pháo lồng giữa hai Mã để cơ động chuyển cánh đánh úp bất ngờ.',
  },
  {
    id: 'don-de-ma',
    name: 'Đơn Đề Mã',
    icon: '🐎',
    count: 2,
    description: 'Thế trận cổ truyền một Mã giữ trung lộ, một Mã biên bảo vệ sườn, phối hợp Pháo tuần hà vững chắc.',
  },
  {
    id: 'tien-nhan',
    name: 'Tiên Nhân Chỉ Lộ',
    icon: '🧭',
    count: 3,
    description: 'Nước mở màn thăm dò ý đồ đối phương đầy mưu lược, công thủ toàn diện với nhiều đường biến hóa sâu sắc.',
  },
  {
    id: 'khoi-ma',
    name: 'Khởi Mã Cuộc',
    icon: '🐴',
    count: 2,
    description: 'Tiên hạ thủ vi cường bằng nước nhảy Mã chắc chắn, hướng ván cờ vào thế trận tàn cuộc đọ nội lực.',
  },
  {
    id: 'phi-tuong',
    name: 'Phi Tượng Cuộc',
    icon: '🐘',
    count: 2,
    description: 'Khai cuộc nhu khắc cương lấy tĩnh chế động, củng cố phòng tuyến vững như bàn thạch trước khi phản công.',
  },
  {
    id: 'qua-cung-si-giac',
    name: 'Quá Cung Pháo & Sĩ Giác Pháo',
    icon: '🎯',
    count: 2,
    description: 'Khai cuộc chuyển Pháo sang cánh đối địch hoặc góc Sĩ để tập trung hỏa lực công phá mạn sườn.',
  },
  {
    id: 'cam-bay-ky-tran',
    name: 'Cạm Bẫy Khai Cuộc & Kỳ Trận',
    icon: '⚡',
    count: 4,
    description: 'Các trận pháp kỳ dị, bẫy đoạt quân bắt Tướng chớp nhoáng (Quy Bối Pháo, Uyên Ương Pháo, Thiết Hoạt Xa).',
  },
];

export const OPENINGS_DATABASE: OpeningVariation[] = [
  // ==========================================
  // 1. TRUNG PHÁO & THUẬN PHÁO
  // ==========================================
  {
    id: 'thuan-phao-hoanh-xa-vs-truc-xa',
    name: 'Thuận Pháo Hiện Đại: Hoành Xe Đối Trực Xe',
    vietnameseName: 'Thuận Pháo Hoành Xe Đối Trực Xe',
    chineseName: '顺炮横车对直车',
    category: 'trung-phao',
    side: 'both',
    eco: 'C01',
    description: 'Cả hai bên cùng vào Pháo đầu cùng cánh. Đỏ khởi Hoành Xe (Xe hoành lên hàng hà), Đen xuất Trực Xe (Xe đi thẳng). Cuộc chiến đối công mãn nhãn giữa tốc độ triển khai quân và khả năng khống chế lộ thông.',
    strategicGoals: [
      'Đỏ dùng Hoành Xe tuần hà để bảo vệ các tuyến Tốt và linh hoạt chuyển sang sườn công kích.',
      'Đen dùng Trực Xe chiếm cứ lộ 8 hoặc 2 uy hiếp cánh mỏng của Đỏ.',
      'Tranh chấp quyền kiểm soát hàng tốt và trung lộ quyết liệt.',
    ],
    strengths: [
      'Thế trận cởi mở, nhiều đòn phối hợp chiến thuật đặc sắc.',
      'Khả năng tạo đột biến cao cho cả hai bên nếu nắm vững lý thuyết.',
    ],
    weaknesses: [
      'Hở sườn lớn nếu một bên phối hợp quân thiếu chặt chẽ.',
      'Rất dễ dính cạm bẫy pháo đầu nếu tính toán sai một nhịp.',
    ],
    grandmasters: ['Hồ Vinh Hoa', 'Hứa Ngân Xuyên', 'Lại Lý Huynh', 'Lữ Khâm'],
    stats: {
      redWinRate: 41,
      drawRate: 35,
      blackWinRate: 24,
      popularity: 92,
      totalGamesSample: 14500,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ vào Trung Pháo kiểm soát trục trung tâm, uy hiếp Tốt đầu của Đen.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen đáp trả bằng Thuận Pháo, cùng dồn hỏa lực vào trung lộ sẵn sàng ăn miếng trả miếng.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ nhảy Mã cánh phải bảo vệ Tốt đầu và phát triển quân nhanh.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy Mã cánh trái đối ứng, giữ chắc trục trung tâm.', isKeyMove: true },
      { from: 'i1', to: 'i2', notation: 'X1.1', commentary: 'Đỏ đi Xe 1 tiến 1 tạo thế Hoành Xe, chuẩn bị bình sang lộ 4 hoặc lộ 6.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Trực Xe nhanh chóng chiếm giữ lộ 8 thông thoáng.', isKeyMove: true },
      { from: 'i2', to: 'e2', notation: 'X1-6', commentary: 'Đỏ bình Xe qua sườn kìm hãm Mã Đen và phối hợp cùng Pháo đầu.', isKeyMove: true },
      { from: 'b10', to: 'b4', notation: 'X8.6', commentary: 'Đen quá hà Xa (Xe qua sông) thọc sâu vào trận địa của Đỏ.', isKeyMove: true },
    ],
    trapsAndMistakes: [
      'Đen không nên vội vã ăn Tốt giữa Đỏ khi chưa phát triển đủ Mã và Xe.',
      'Đỏ cần chú ý tránh để Xe Đen kẹp nách bắt đôi Pháo Mã.',
    ],
  },
  {
    id: 'thuan-phao-truc-xa-vs-hoanh-xa',
    name: 'Thuận Pháo: Trực Xe Đối Hoành Xe',
    vietnameseName: 'Thuận Pháo Trực Xe Đối Hoành Xe',
    chineseName: '顺炮直车对横车',
    category: 'trung-phao',
    side: 'both',
    eco: 'C02',
    description: 'Đỏ ra Trực Xe nhanh chiếm lộ thông, Đen dùng Hoành Xe linh hoạt phòng ngự và chờ thời cơ phản kích vào cánh yếu của Đỏ.',
    strategicGoals: [
      'Đỏ tận dụng ưu thế đi trước tấn công nhanh bằng Trực Xe đè ép cánh Mã của Đen.',
      'Đen hoành Xe tuần hà để bảo vệ tuyến Tốt và che chắn sườn yếu.',
    ],
    strengths: [
      'Đỏ có thế trận chủ động, ép đối phương vào thế phòng thủ bị động.',
    ],
    weaknesses: [
      'Nếu công không thành, Đỏ dễ bị Đen phản kích bằng Pháo cánh.',
    ],
    grandmasters: ['Vương Thiên Nhất', 'Trịnh Duy Đồng', 'Nguyễn Thành Bảo'],
    stats: {
      redWinRate: 43,
      drawRate: 34,
      blackWinRate: 23,
      popularity: 88,
      totalGamesSample: 11200,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo khai màn áp lực trung lộ.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Thuận Pháo nghênh chiến.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã phát triển giữ Tốt giữa.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã Đen lên giữ Tốt đầu.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe chiếm lộ 2 khống chế mặt trận.', isKeyMove: true },
      { from: 'a10', to: 'a9', notation: 'X9.1', commentary: 'Đen hoành Xe 9 tiến 1 chuẩn bị chuyển cánh đối kháng.', isKeyMove: true },
      { from: 'h1', to: 'h5', notation: 'X2.4', commentary: 'Đỏ tuần hà Xa (Xe tiến 4) phong tỏa tuyến Tốt của Đen.', isKeyMove: true },
      { from: 'a9', to: 'd9', notation: 'X9-4', commentary: 'Đen bình Xe lộ 4 chiếm trục quan trọng giải tỏa áp lực.', isKeyMove: true },
    ],
  },
  {
    id: 'trung-phao-qua-ha-xa-vs-binh-phong-ma',
    name: 'Trung Pháo Quá Hà Xa Đối Bình Phong Mã',
    vietnameseName: 'Trung Pháo Quá Hà Xa Đối Bình Phong Mã',
    chineseName: '中炮过河车对屏风马',
    category: 'trung-phao',
    side: 'red',
    eco: 'C10',
    description: 'Đòn công kích kinh điển bậc nhất: Đỏ thúc Xe qua sông nhằm chia cắt và khống chế đôi Mã uy lực của Đen. Đây là chiến trường thử thách độ sâu tính toán của mọi đại kỳ thủ.',
    strategicGoals: [
      'Đỏ dùng Xe quá hà đè ép Mã cánh hoặc bắt Tốt đầu/Tốt biên của Đen.',
      'Tạo áp lực liên tục lên cánh yếu để mở đường cho Pháo Mã ồ ạt xông lên.',
    ],
    strengths: [
      'Khả năng tấn công vũ bão, chiếm quyền chủ động tuyệt đối trong trung cuộc.',
    ],
    weaknesses: [
      'Xe quá hà đơn độc nếu bị Đen bình Pháo đổi Xe hoặc giam hãm sẽ mất tiên.',
    ],
    grandmasters: ['Hồ Vinh Hoa', 'Liễu Đại Hoa', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 39,
      drawRate: 41,
      blackWinRate: 20,
      popularity: 95,
      totalGamesSample: 22000,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo tiến công trung lộ.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen nhảy Mã 2 tiến 3 dựng lá chắn đầu tiên.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ phát triển Mã phải tương ứng.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã 8 tiến 7 hoàn thành trận hình Bình Phong Mã vững chãi.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe chiếm lộ 2.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe 9 bình 8 phong tỏa cánh Pháo của Đỏ.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xa (Xe tiến 6) vượt sông đè ép trực tiếp trận địa Đen.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen tấn Tốt 7 thông đường cho Mã 7 chuẩn bị phản công.', isKeyMove: true },
    ],
  },
  {
    id: 'trung-phao-tuan-ha-xa-vs-binh-phong-ma',
    name: 'Trung Pháo Tuần Hà Xa Đối Bình Phong Mã',
    vietnameseName: 'Trung Pháo Tuần Hà Xa Đối Bình Phong Mã',
    chineseName: '中炮巡河车对屏风马',
    category: 'trung-phao',
    side: 'red',
    eco: 'C11',
    description: 'Đỏ không vội qua sông mà dừng Xe ở bờ sông (tiến 4) để củng cố hàng Tốt, giữ thế trận ổn định rồi từ từ siết chặt vòng vây.',
    strategicGoals: [
      'Kiểm soát toàn bộ hàng Tốt (hàng hà), ngăn chặn Đen thúc Tốt 3 hoặc Tốt 7 qua sông.',
      'Bảo vệ cánh mỏng và tạo thế liên kết vững chắc giữa Pháo, Mã và Xe.',
    ],
    strengths: [
      'Trận hình kín kẽ, thế trận chắc chắn khó bị phản kích.',
    ],
    weaknesses: [
      'Sức ép lên trận địa đối phương diễn ra chậm hơn Quá Hà Xa.',
    ],
    grandmasters: ['Hứa Ngân Xuyên', 'Triệu Quốc Vinh', 'Vương Thiên Nhất'],
    stats: {
      redWinRate: 38,
      drawRate: 46,
      blackWinRate: 16,
      popularity: 84,
      totalGamesSample: 9800,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo khai cuộc.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã Đen lên giữ trung lộ.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ phát triển bảo vệ Tốt đầu.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã hoàn chỉnh.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe đối ứng.', isKeyMove: true },
      { from: 'h1', to: 'h5', notation: 'X2.4', commentary: 'Đỏ Tuần Hà Xa (Xe tiến 4) chiếm lĩnh bờ sông vững vàng.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen thúc Tốt 7 mở đường cho Mã trái.', isKeyMove: true },
    ],
  },
  {
    id: 'trung-phao-that-binh-vs-binh-phong-ma',
    name: 'Trung Pháo Tiến Thất Binh Đối Bình Phong Mã',
    vietnameseName: 'Trung Pháo Tiến Thất Binh Đối Bình Phong Mã',
    chineseName: '中炮进七兵对屏风马',
    category: 'trung-phao',
    side: 'red',
    eco: 'C12',
    description: 'Đỏ thúc Tốt 7 (C7.1) nhằm hạn chế Mã 3 của Đen và mở rộng đường cho Mã Đỏ nhảy lên ngọa tào uy hiếp.',
    strategicGoals: [
      'Khóa chặt đầu Mã Đen ở lộ 3, chuẩn bị nhảy Mã Đỏ qua sông.',
      'Mở thế trận tấn công cánh trái của Đen một cách bài bản.',
    ],
    strengths: ['Tạo thế công kích sâu sắc, khống chế không gian tốt.'],
    weaknesses: ['Dễ bị Đen phản công bằng đòn Bình Pháo Đổi Xe hoặc Mã Bàn Hà.'],
    grandmasters: ['Tưởng Xuyên', 'Lại Lý Huynh', 'Trịnh Duy Đồng'],
    stats: {
      redWinRate: 37,
      drawRate: 43,
      blackWinRate: 20,
      popularity: 89,
      totalGamesSample: 13500,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo chủ công.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã Đen lên trận.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ xuất trận.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã thành hình.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe xuất trận.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen đối Xe.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ tấn Binh 7 (Thất Binh) khóa đầu Mã Đen.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen cũng đáp trả bằng Tiến Binh 7.', isKeyMove: true },
    ],
  },
  {
    id: 'trung-phao-tam-binh-vs-binh-phong-ma',
    name: 'Trung Pháo Tiến Tam Binh Đối Bình Phong Mã',
    vietnameseName: 'Trung Pháo Tiến Tam Binh Đối Bình Phong Mã',
    chineseName: '中炮进三兵对屏风马',
    category: 'trung-phao',
    side: 'red',
    eco: 'C13',
    description: 'Đỏ thúc Tốt 3 (C3.1) kích hoạt Mã cánh phải, nhắm thẳng vào cánh trái sơ hở của Đen để tạo nên những trận đối công tinh tế bậc nhất.',
    strategicGoals: [
      'Kích hoạt Mã 3 tấn 4 hoặc tấn 2 thâm nhập sườn Đen.',
      'Phối hợp với Pháo lộ 8 tạo thế gọng kìm hai cánh.',
    ],
    strengths: ['Công thủ linh hoạt, cấu trúc Tốt rất bền vững.'],
    weaknesses: ['Đòi hỏi sự am hiểu sâu về chuyển tàn cuộc.'],
    grandmasters: ['Hứa Ngân Xuyên', 'Hồ Vinh Hoa', 'Uông Dương'],
    stats: {
      redWinRate: 36,
      drawRate: 48,
      blackWinRate: 16,
      popularity: 87,
      totalGamesSample: 12000,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã vững chắc.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Xuất Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Xuất Xe nghênh chiến.', isKeyMove: true },
      { from: 'g4', to: 'g5', notation: 'C3.1', commentary: 'Đỏ thúc Tam Binh kích hoạt cánh phải.', isKeyMove: true },
      { from: 'g7', to: 'g6', notation: 'B3.1', commentary: 'Đen cũng thúc Tam Binh tương ứng kiềm tỏa.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 2. BÌNH PHONG MÃ (ĐI HẬU)
  // ==========================================
  {
    id: 'binh-phong-ma-binh-phao-doi-xe',
    name: 'Bình Phong Mã: Bình Pháo Đổi Xe',
    vietnameseName: 'Bình Phong Mã Bình Pháo Đổi Xe',
    chineseName: '屏风马平炮兑车',
    category: 'binh-phong-ma',
    side: 'black',
    eco: 'B01',
    description: 'Chiêu thức phòng ngự phản công nổi tiếng nhất của Đen: Khi Đỏ xuất Xe quá hà uy hiếp, Đen bình Pháo lộ 8 sang lộ 9 hoặc lộ 2 để gạ đổi Xe, hóa giải mũi nhọn tấn công của Đỏ ngay từ trong trứng nước.',
    strategicGoals: [
      'Hóa giải triệt để mũi nhọn Xe quá hà của Đỏ.',
      'Mở đường cho Xe 8 của Đen xuất trận và giành quyền chủ động cánh phải.',
    ],
    strengths: ['Thế trận cực kỳ chắc chắn, an toàn tối đa cho bên Hậu.'],
    weaknesses: ['Dễ dẫn đến thế hòa nếu Đỏ chấp nhận đổi quân sớm.'],
    grandmasters: ['Hồ Vinh Hoa', 'Hứa Ngân Xuyên', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 30,
      drawRate: 52,
      blackWinRate: 18,
      popularity: 96,
      totalGamesSample: 18900,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ vào Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen nhảy Mã phải.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ nhảy Mã.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen dựng Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ ra Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ thúc Xe quá hà đè Mã.', isKeyMove: true },
      { from: 'b8', to: 'a8', notation: 'P8-9', commentary: 'Đen Bình Pháo Đổi Xe tuyệt kỹ, vô hiệu hóa hoàn toàn Xe Đỏ!', isKeyMove: true },
    ],
  },
  {
    id: 'binh-phong-ma-ta-ma-ban-ha',
    name: 'Bình Phong Mã: Tả Mã Bàn Hà',
    vietnameseName: 'Bình Phong Mã Tả Mã Bàn Hà',
    chineseName: '屏风马左马盘河',
    category: 'binh-phong-ma',
    side: 'black',
    eco: 'B02',
    description: 'Đen chủ động nhảy Mã 7 vượt sông (Tả Mã Bàn Hà) lao thẳng vào trung tuyến của Đỏ, đe dọa ăn Tốt giữa và tạo nên cuộc đối công long trời lở đất.',
    strategicGoals: [
      'Mã Đen nhảy qua sông đe dọa các điểm yếu ở lộ 3 và lộ 5 của Đỏ.',
      'Gây rối loạn hàng ngũ Đỏ và chuyển từ phòng thủ sang đại phản công.',
    ],
    strengths: ['Sức tấn công dũng mãnh bất ngờ, gây sức ép tâm lý lớn cho bên Tiên.'],
    weaknesses: ['Nếu Mã bị vây bắt, Đen sẽ mất quân hoặc hở sườn nghiêm trọng.'],
    grandmasters: ['Vương Thiên Nhất', 'Liễu Đại Hoa', 'Nguyễn Hoàng Lâm'],
    stats: {
      redWinRate: 35,
      drawRate: 38,
      blackWinRate: 27,
      popularity: 90,
      totalGamesSample: 14200,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen thúc Tốt 7 mở đường cho Tả Mã vượt sông.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Thất Binh.', isKeyMove: true },
      { from: 'c8', to: 'd6', notation: 'M7.6', commentary: 'Đen nhảy Tả Mã Bàn Hà qua sông tấn công thần tốc!', isKeyMove: true },
    ],
  },
  {
    id: 'binh-phong-ma-phi-huu-tuong',
    name: 'Bình Phong Mã: Phi Hữu Tượng (Củng Cố Trung Tuyến)',
    vietnameseName: 'Bình Phong Mã Phi Hữu Tượng',
    chineseName: '屏风马飞右象',
    category: 'binh-phong-ma',
    side: 'black',
    eco: 'B03',
    description: 'Đen chủ động bay Tượng phải (Tượng 3 tiến 5) củng cố trung lộ vững chắc trước khi mở đường xuất quân, trận hình vững như trường thành.',
    strategicGoals: [
      'Gia cố trung lộ chống lại đòn đánh trực diện từ Trung Pháo.',
      'Liên kết đôi Sĩ Tượng tạo phòng tuyến đa tầng không sơ hở.',
    ],
    strengths: ['Khó bị xuyên phá, an toàn cao khi đấu với đối thủ mạnh.'],
    weaknesses: ['Nhịp tấn công chậm, nhường quyền kiểm soát thế trận cho Đỏ.'],
    grandmasters: ['Hứa Ngân Xuyên', 'Lữ Khâm'],
    stats: {
      redWinRate: 32,
      drawRate: 50,
      blackWinRate: 18,
      popularity: 82,
      totalGamesSample: 7600,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Xuất Xe.', isKeyMove: true },
      { from: 'g4', to: 'g5', notation: 'C3.1', commentary: 'Đỏ thúc Tam Binh.', isKeyMove: true },
      { from: 'g10', to: 'e8', notation: 'T3.5', commentary: 'Đen Phi Hữu Tượng cố thủ trung lộ vững như bàn thạch.', isKeyMove: true },
    ],
  },
  {
    id: 'binh-phong-ma-hoanh-xa-tuyen-ha',
    name: 'Bình Phong Mã: Hoành Xe Tuyến Hà',
    vietnameseName: 'Bình Phong Mã Hoành Xe Tuyến Hà',
    chineseName: '屏风马横车巡河',
    category: 'binh-phong-ma',
    side: 'black',
    eco: 'B04',
    description: 'Đen không đi Trực Xe mà dùng Hoành Xe dâng lên hàng hà cơ động, vừa giữ Tốt vừa sẵn sàng tràn sang cánh trái tiếp viện.',
    strategicGoals: ['Linh hoạt đổi cánh phòng thủ và tấn công bất ngờ.'],
    strengths: ['Tạo thế trận đa biến, khó bị bắt bài.'],
    weaknesses: ['Tốn nhiều nước đi Xe.'],
    grandmasters: ['Hồ Vinh Hoa', 'Trịnh Duy Đồng'],
    stats: {
      redWinRate: 34,
      drawRate: 44,
      blackWinRate: 22,
      popularity: 79,
      totalGamesSample: 6500,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'a9', notation: 'X9.1', commentary: 'Đen khởi Hoành Xe linh hoạt.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà đè Mã.', isKeyMove: true },
      { from: 'a9', to: 'f9', notation: 'X9-4', commentary: 'Đen bình Xe lộ 4 chiếm trục hiểm yếu.', isKeyMove: true },
    ],
  },
  {
    id: 'binh-phong-ma-song-phao-qua-ha',
    name: 'Bình Phong Mã: Song Pháo Quá Hà (Chiến Thuật Phục Kích)',
    vietnameseName: 'Bình Phong Mã Song Pháo Quá Hà',
    chineseName: '屏风马双炮过河',
    category: 'binh-phong-ma',
    side: 'black',
    eco: 'B05',
    description: 'Đen táo bạo đẩy cả hai Pháo vượt sông khống chế bờ sông của Đỏ, tạo thế bao vây và uy hiếp Xe Pháo Đỏ trong đòn đối công cực kỳ kịch tính.',
    strategicGoals: ['Khống chế toàn bộ bờ sông của đối phương, gài bẫy bắt quân.'],
    strengths: ['Sức ép tâm lý khủng khiếp, phản đòn cực gắt.'],
    weaknesses: ['Hậu phương mỏng, nếu bị phản kích trung lộ sẽ tan vỡ nhanh.'],
    grandmasters: ['Vương Thiên Nhất', 'Nguyễn Thành Bảo'],
    stats: {
      redWinRate: 36,
      drawRate: 34,
      blackWinRate: 30,
      popularity: 81,
      totalGamesSample: 5200,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Xuất Xe.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xa.', isKeyMove: true },
      { from: 'b8', to: 'b5', notation: 'P8.5', commentary: 'Đen phi Pháo qua sông phong tỏa trận địa Đỏ!', isKeyMove: true },
    ],
  },

  // ==========================================
  // 3. NGHỊCH PHÁO (LIỆT THỦ PHÁO)
  // ==========================================
  {
    id: 'nghich-phao-hoanh-xa-vs-truc-xa',
    name: 'Nghịch Pháo Hiện Đại: Hoành Xe Đối Trực Xe',
    vietnameseName: 'Nghịch Pháo Hoành Xe Đối Trực Xe',
    chineseName: '逆炮横车对直车',
    category: 'nghich-phao',
    side: 'both',
    eco: 'N01',
    description: 'Hai bên cùng vào Pháo đầu nhưng ngược cánh nhau (Đỏ Pháo 2-5, Đen Pháo 2-5). Đây là trận đồ sinh tử khét tiếng trong Cờ Tướng, nơi không có chỗ cho sự do dự!',
    strategicGoals: [
      'Công phá trực diện cánh đối diện của đối phương.',
      'Tập trung tốc độ tấn công, bên nào nhanh hơn một nhịp sẽ giành chiến thắng áp đảo.',
    ],
    strengths: ['Tạo thế trận tấn công bão táp, đòn đánh sắc như dao cạo.'],
    weaknesses: ['Phòng ngự lỏng lẻo, rủi ro thua cuộc cực cao nếu tính toán sai.'],
    grandmasters: ['Liễu Đại Hoa', 'Vương Gia Lương', 'Trần Quới'],
    stats: {
      redWinRate: 46,
      drawRate: 20,
      blackWinRate: 34,
      popularity: 88,
      totalGamesSample: 8900,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ vào Trung Pháo hữu.', isKeyMove: true },
      { from: 'h8', to: 'e8', notation: 'P2-5', commentary: 'Đen vào Nghịch Pháo (Pháo 2-5) tuyên chiến trực diện!', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ xuất quân giữ Tốt.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã Đen lên giữ Tốt tương ứng.', isKeyMove: true },
      { from: 'i1', to: 'i2', notation: 'X1.1', commentary: 'Đỏ khởi Hoành Xe chuẩn bị đánh sườn.', isKeyMove: true },
      { from: 'i10', to: 'h10', notation: 'X1-2', commentary: 'Đen xuất Trực Xe chiếm lộ 2 thông thoáng.', isKeyMove: true },
      { from: 'i2', to: 'e2', notation: 'X1-6', commentary: 'Đỏ bình Xe lộ 6 kẹp chặt cánh Đen.', isKeyMove: true },
      { from: 'h10', to: 'h6', notation: 'X2.6', commentary: 'Đen xông Xe qua sông phản kích dữ dội!', isKeyMove: true },
    ],
  },
  {
    id: 'liet-thu-phao-co-dien',
    name: 'Liệt Thủ Pháo Cổ Điển (Đại Đối Công)',
    vietnameseName: 'Liệt Thủ Pháo Cổ Điển',
    chineseName: '列手炮经典对攻',
    category: 'nghich-phao',
    side: 'both',
    eco: 'N02',
    description: 'Thế cờ cổ điển hàng trăm năm lịch sử: Đỏ công cánh trái, Đen dồn lực công cánh phải, tạo nên bức tranh đối công rực lửa.',
    strategicGoals: ['Đánh sập phòng tuyến cánh của đối phương trước khi bị chiếu bí.'],
    strengths: ['Trận đấu kết thúc nhanh, tính cống hiến rất cao.'],
    weaknesses: ['Ít xuất hiện ở đỉnh cao do tính mạo hiểm quá lớn.'],
    grandmasters: ['Vương Gia Lương', 'Hồ Vinh Hoa'],
    stats: {
      redWinRate: 48,
      drawRate: 18,
      blackWinRate: 34,
      popularity: 75,
      totalGamesSample: 4300,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h8', to: 'e8', notation: 'P2-5', commentary: 'Nghịch Pháo.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'i10', to: 'i9', notation: 'X1.1', commentary: 'Đen đáp trả bằng Hoành Xe.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xe.', isKeyMove: true },
      { from: 'i9', to: 'e9', notation: 'X1-6', commentary: 'Đen hoành Xe sang sườn uy hiếp Pháo đầu Đỏ!', isKeyMove: true },
    ],
  },
  {
    id: 'nghich-phao-thiet-ke',
    name: 'Nghịch Pháo: Thiết Kế Bẫy Mã Khởi',
    vietnameseName: 'Nghịch Pháo Bẫy Mã Khởi',
    chineseName: '逆炮弃马陷阱',
    category: 'nghich-phao',
    side: 'both',
    eco: 'N03',
    description: 'Biến thể kỳ ảo của Nghịch Pháo với đòn thí Tốt tranh tiên và gài bẫy bắt Xe cực kỳ hiểm hóc.',
    strategicGoals: ['Tranh tiên đoạt thế bằng những nước thí quân ngoạn mục.'],
    strengths: ['Bẫy rất khó phát hiện nếu đối thủ thiếu kinh nghiệm.'],
    weaknesses: ['Nếu đối phương phòng ngự chuẩn xác sẽ bị thiệt quân.'],
    grandmasters: ['Liễu Đại Hoa'],
    stats: {
      redWinRate: 44,
      drawRate: 22,
      blackWinRate: 34,
      popularity: 70,
      totalGamesSample: 3100,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h8', to: 'e8', notation: 'P2-5', commentary: 'Nghịch Pháo.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã phải giữ Tốt đầu.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã đối xứng.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe cánh phải.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy tiếp Mã 8 tiến 7.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xe.', isKeyMove: true },
      { from: 'g7', to: 'g6', notation: 'B3.1', commentary: 'Đen tấn Tốt 3 phản đòn linh diệu.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 4. PHẢN CUNG MÃ (GIÁP PHÁO XUYÊN CUNG)
  // ==========================================
  {
    id: 'phan-cung-ma-tien-tam-binh',
    name: 'Phản Cung Mã Tiến Tam Binh (Trận Pháp Uyển Chuyển)',
    vietnameseName: 'Phản Cung Mã Tiến Tam Binh',
    chineseName: '反宫马进三兵',
    category: 'phan-cung-ma',
    side: 'black',
    eco: 'P01',
    description: 'Trận đồ lừng danh do Hồ Vinh Hoa nâng tầm thành tuyệt nghệ: Một Pháo kẹp giữa hai Mã (Sĩ Giác Pháo), bảo vệ trung lộ chắc chắn đồng thời có khả năng chuyển cánh công thủ cực kỳ linh hoạt.',
    strategicGoals: [
      'Dùng Pháo xuyên cung bảo vệ Tốt đầu và hỗ trợ đôi Mã.',
      'Khống chế đòn đánh trung lộ của Trung Pháo và phản kích cánh mỏng.',
    ],
    strengths: ['Cực kỳ dẻo dai, khắc chế tốt lối đánh Trung Pháo cứng nhắc.'],
    weaknesses: ['Đòi hỏi kỳ thủ phải có trình độ trung tàn cuộc uyên thâm.'],
    grandmasters: ['Hồ Vinh Hoa', 'Lại Lý Huynh', 'Tưởng Xuyên'],
    stats: {
      redWinRate: 33,
      drawRate: 46,
      blackWinRate: 21,
      popularity: 88,
      totalGamesSample: 11000,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ vào Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã phải.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã phải.', isKeyMove: true },
      { from: 'b8', to: 'd8', notation: 'P8-6', commentary: 'Đen vào Sĩ Giác Pháo (Pháo 8 bình 6) hình thành khung Phản Cung Mã!', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy tiếp Mã 8 tiến 7 hoàn thiện Giáp Pháo Xuyên Cung hoàn mỹ.', isKeyMove: true },
      { from: 'g4', to: 'g5', notation: 'C3.1', commentary: 'Đỏ thúc Tam Binh.', isKeyMove: true },
      { from: 'g7', to: 'g6', notation: 'B3.1', commentary: 'Đen thúc Tam Binh giữ cân bằng.', isKeyMove: true },
    ],
  },
  {
    id: 'phan-cung-ma-tien-that-binh',
    name: 'Phản Cung Mã Tiến Thất Binh',
    vietnameseName: 'Phản Cung Mã Tiến Thất Binh',
    chineseName: '反宫马进七兵',
    category: 'phan-cung-ma',
    side: 'black',
    eco: 'P02',
    description: 'Biến thể thúc Tốt 7 tạo đường cho Mã 7 nhảy qua sông phản kích nhanh chóng.',
    strategicGoals: ['Mở thông lộ Mã cánh trái tấn công bờ sông Đỏ.'],
    strengths: ['Tính cơ động cao, phản công nhanh chóng.'],
    weaknesses: ['Dễ bị Đỏ khoét sâu vào lộ 3.'],
    grandmasters: ['Hồ Vinh Hoa', 'Hứa Ngân Xuyên'],
    stats: {
      redWinRate: 35,
      drawRate: 43,
      blackWinRate: 22,
      popularity: 81,
      totalGamesSample: 6700,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b8', to: 'd8', notation: 'P8-6', commentary: 'Phản Cung Pháo.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Hoàn thành Phản Cung Mã.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Thất Binh.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen thúc Thất Binh tương ứng.', isKeyMove: true },
    ],
  },
  {
    id: 'phan-cung-ma-hoanh-xa-phan-kich',
    name: 'Phản Cung Mã: Hoành Xe Phản Kích',
    vietnameseName: 'Phản Cung Mã Hoành Xe Phản Kích',
    chineseName: '反宫马横车反击',
    category: 'phan-cung-ma',
    side: 'black',
    eco: 'P03',
    description: 'Đen kết hợp Phản Cung Mã với Hoành Xe tạo nên lá chắn kiên cố kiêm mũi nhọn phản kích sườn hiểm hóc.',
    strategicGoals: ['Hoành Xe giữ tuyến Tốt và phối hợp Pháo công kích cánh.'],
    strengths: ['Độ biến hóa sâu sắc, dễ bẫy đối phương lơ là.'],
    weaknesses: ['Cần phối hợp nhiều quân nhịp nhàng.'],
    grandmasters: ['Hồ Vinh Hoa', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 33,
      drawRate: 45,
      blackWinRate: 22,
      popularity: 76,
      totalGamesSample: 4500,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b8', to: 'd8', notation: 'P8-6', commentary: 'Pháo 8 bình 6.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã 8 tiến 7.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xe.', isKeyMove: true },
      { from: 'a10', to: 'a9', notation: 'X9.1', commentary: 'Đen khởi Hoành Xe phản kích!', isKeyMove: true },
    ],
  },

  // ==========================================
  // 5. ĐƠN ĐỀ MÃ
  // ==========================================
  {
    id: 'don-de-ma-huu-don-de',
    name: 'Đơn Đề Mã Hữu: Thế Trận Cổ Truyền',
    vietnameseName: 'Đơn Đề Mã Hữu',
    chineseName: '单提马右单提',
    category: 'don-de-ma',
    side: 'black',
    eco: 'D01',
    description: 'Một Mã giữ trung lộ (Mã 2 tiến 3), một Mã nhảy biên (Mã 8 tiến 9). Trận thế cổ kính mang tính phòng thủ chắc chắn và ẩn chứa nhiều đòn phục kích cánh.',
    strategicGoals: ['Giải tỏa tắc nghẽn trung lộ, tạo đường thông cho Xe Pháo biên.'],
    strengths: ['Bảo vệ Tốt biên tốt, Xe xuất quân rất nhanh.'],
    weaknesses: ['Trung lộ có phần mỏng hơn Bình Phong Mã.'],
    grandmasters: ['Dương Quan Lân', 'Hồ Vinh Hoa'],
    stats: {
      redWinRate: 38,
      drawRate: 42,
      blackWinRate: 20,
      popularity: 73,
      totalGamesSample: 5100,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3 giữ Tốt.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ xuất quân.', isKeyMove: true },
      { from: 'b10', to: 'a8', notation: 'M8.9', commentary: 'Đen nhảy Mã biên (Mã 8 tiến 9) tạo thế Đơn Đề Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ ra Trực Xe.', isKeyMove: true },
      { from: 'b8', to: 'd8', notation: 'P8-6', commentary: 'Đen vào Sĩ Giác Pháo củng cố trung tuyến.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ quá hà Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe đối ứng.', isKeyMove: true },
    ],
  },
  {
    id: 'don-de-ma-hoanh-xa',
    name: 'Đơn Đề Mã Hoành Xe Quá Hà',
    vietnameseName: 'Đơn Đề Mã Hoành Xe',
    chineseName: '单提马横车过河',
    category: 'don-de-ma',
    side: 'black',
    eco: 'D02',
    description: 'Biến thể chủ động dùng Hoành Xe phối hợp với Mã biên để đánh phá sườn Đỏ.',
    strategicGoals: ['Dùng Xe hoành qua sông đè ép Tốt và Mã Đỏ.'],
    strengths: ['Tạo bất ngờ lớn cho đối phương.'],
    weaknesses: ['Dễ bị Đỏ đánh vỗ mặt trung lộ nếu phòng thủ sơ hở.'],
    grandmasters: ['Dương Quan Lân'],
    stats: {
      redWinRate: 39,
      drawRate: 40,
      blackWinRate: 21,
      popularity: 68,
      totalGamesSample: 3200,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã lên.', isKeyMove: true },
      { from: 'b10', to: 'a8', notation: 'M8.9', commentary: 'Đơn Đề Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'a9', notation: 'X9.1', commentary: 'Hoành Xe.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Thúc Thất Binh.', isKeyMove: true },
      { from: 'a9', to: 'd9', notation: 'X9-4', commentary: 'Xe bình lộ 4.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 6. TIÊN NHÂN CHỈ LỘ
  // ==========================================
  {
    id: 'tien-nhan-chi-lo-vs-doi-binh-cuc',
    name: 'Tiên Nhân Chỉ Lộ Đối Đối Binh Cục',
    vietnameseName: 'Tiên Nhân Chỉ Lộ Đối Đối Binh Cục',
    chineseName: '仙人指路对对兵局',
    category: 'tien-nhan',
    side: 'both',
    eco: 'T01',
    description: 'Đỏ đi trước thúc Tốt 7 (Binh 7 tiến 1) thăm dò đối phương. Đen đáp trả bằng Binh 7 tiến 1 tương ứng. Cuộc cờ phát triển theo hướng nội lực thâm hậu, tinh vi từng nước đi.',
    strategicGoals: [
      'Thăm dò ý đồ triển khai quân của đối phương.',
      'Khống chế đường nhảy Mã của đối thủ từ sớm và chuẩn bị chuyển Pháo hoặc Mã tùy cơ ứng biến.',
    ],
    strengths: ['Công thủ toàn diện, không lộ sơ hở sớm.'],
    weaknesses: ['Cần khả năng đọc thế trận tàn cuộc xuất sắc.'],
    grandmasters: ['Hứa Ngân Xuyên', 'Vương Thiên Nhất', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 35,
      drawRate: 50,
      blackWinRate: 15,
      popularity: 91,
      totalGamesSample: 16800,
    },
    moves: [
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ mở màn Tiên Nhân Chỉ Lộ (Binh 7 tiến 1) đầy mưu lược.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen Đối Binh Cục (Tốt 7 tiến 1) giữ cân bằng cục diện.', isKeyMove: true },
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ chuyển Trung Pháo tấn công trung lộ.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã 8 tiến 7 vững vàng.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã phải bảo vệ Tốt đầu.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen dựng Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe tương ứng.', isKeyMove: true },
    ],
  },
  {
    id: 'tien-nhan-chi-lo-vs-qua-cung-phao',
    name: 'Tiên Nhân Chỉ Lộ Đối Quá Cung Pháo',
    vietnameseName: 'Tiên Nhân Chỉ Lộ Đối Quá Cung Pháo',
    chineseName: '仙人指路对过宫炮',
    category: 'tien-nhan',
    side: 'both',
    eco: 'T02',
    description: 'Đỏ thúc Tốt 7, Đen đáp trả bằng Pháo 2 bình 6 (Quá Cung Pháo) nhắm thẳng vào cánh mỏng của Đỏ để phản kích.',
    strategicGoals: ['Đen dồn Pháo sang cánh đối địch để phản đòn.'],
    strengths: ['Đột phá bất ngờ vào cánh yếu.'],
    weaknesses: ['Nếu Đỏ chuyển Phi Tượng hoặc Trung Pháo kịp thời sẽ hóa giải dễ dàng.'],
    grandmasters: ['Triệu Hâm Hâm', 'Uông Dương'],
    stats: {
      redWinRate: 37,
      drawRate: 45,
      blackWinRate: 18,
      popularity: 83,
      totalGamesSample: 8200,
    },
    moves: [
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Tiên Nhân Chỉ Lộ.', isKeyMove: true },
      { from: 'h8', to: 'd8', notation: 'P2-6', commentary: 'Đen vào Quá Cung Pháo phản kích.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ xuất quân.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã Đen lên trận.', isKeyMove: true },
      { from: 'g1', to: 'e3', notation: 'T7.5', commentary: 'Đỏ Phi Tượng củng cố trung lộ.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã hoàn chỉnh trận hình.', isKeyMove: true },
    ],
  },
  {
    id: 'tien-nhan-chi-lo-vs-ta-trung-phao',
    name: 'Tiên Nhân Chỉ Lộ Đối Tả Trung Pháo',
    vietnameseName: 'Tiên Nhân Chỉ Lộ Đối Tả Trung Pháo',
    chineseName: '仙人指路对左中炮',
    category: 'tien-nhan',
    side: 'both',
    eco: 'T03',
    description: 'Đỏ đi Tốt 7, Đen lập tức vào Pháo 8 bình 5 (Tả Trung Pháo) đe dọa trực diện Tốt đầu của Đỏ nhằm đoạt quyền chủ động.',
    strategicGoals: ['Đen dùng Pháo đầu tấn công chớp nhoáng ép Đỏ phòng ngự.'],
    strengths: ['Sức ép lớn lên trung lộ Đỏ ngay từ đầu.'],
    weaknesses: ['Đỏ có Tốt 7 đã thông đường nên phản kích cánh rất mạnh.'],
    grandmasters: ['Vương Thiên Nhất', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 40,
      drawRate: 40,
      blackWinRate: 20,
      popularity: 85,
      totalGamesSample: 9400,
    },
    moves: [
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Tiên Nhân Chỉ Lộ mở màn.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen Tả Trung Pháo vỗ mặt!', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã Đỏ giữ Tốt đầu.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã Đen lên trận.', isKeyMove: true },
      { from: 'g1', to: 'e3', notation: 'T7.5', commentary: 'Đỏ Phi Tượng gia cố trung lộ.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe chiếm lộ 8.', isKeyMove: true },
      { from: 'b1', to: 'c3', notation: 'M8.7', commentary: 'Đỏ lên tiếp Mã 8 tiến 7 vững như bàn thạch.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã hoàn chỉnh trận hình.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 7. KHỞI MÃ CUỘC
  // ==========================================
  {
    id: 'khoi-ma-cuoc-vs-de-binh',
    name: 'Khởi Mã Cuộc Đối Đề Binh Cục (Tiến Tốt 7)',
    vietnameseName: 'Khởi Mã Cuộc Đối Đề Binh',
    chineseName: '起马局对进卒',
    category: 'khoi-ma',
    side: 'both',
    eco: 'K01',
    description: 'Đỏ đi nước đầu nhảy Mã 2 tiến 3 hoặc Mã 8 tiến 7 vững chắc. Đen đáp lại bằng Tiến Tốt 7 hoặc Tốt 3 nhằm hạn chế tầm hoạt động của Mã Đỏ.',
    strategicGoals: ['Đỏ phát triển quân nhẹ nhàng, kiểm soát ô trung tâm và sẵn sàng chuyển Pháo.'],
    strengths: ['Thế trận cực kỳ vững chãi, ít sơ hở.'],
    weaknesses: ['Sức ép ban đầu lên đối thủ không cao.'],
    grandmasters: ['Hứa Ngân Xuyên', 'Triệu Quốc Vinh'],
    stats: {
      redWinRate: 34,
      drawRate: 52,
      blackWinRate: 14,
      popularity: 80,
      totalGamesSample: 7800,
    },
    moves: [
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ khởi Mã 2 tiến 3 mở màn.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen tiến Tốt 7 kiềm chế bước tiến của Mã.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Tốt 7 thông đường tương ứng.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy Mã 8 tiến 7.', isKeyMove: true },
      { from: 'b3', to: 'e3', notation: 'P8-5', commentary: 'Đỏ chuyển Pháo 8 bình 5 vào trung lộ tấn công.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen dựng Bình Phong Mã.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe cánh phải.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe đối ứng.', isKeyMove: true },
    ],
  },
  {
    id: 'khoi-ma-cuoc-vs-trung-phao',
    name: 'Khởi Mã Cuộc Đối Trung Pháo',
    vietnameseName: 'Khởi Mã Cuộc Đối Trung Pháo',
    chineseName: '起马局对中炮',
    category: 'khoi-ma',
    side: 'both',
    eco: 'K02',
    description: 'Đỏ nhảy Mã trước, Đen vào Trung Pháo ngay nước đầu để tranh tiên đoạt quyền chủ động.',
    strategicGoals: ['Đen dùng Trung Pháo ép Đỏ phải phòng thủ trung lộ.'],
    strengths: ['Đột phá nhanh vào điểm yếu trung lộ.'],
    weaknesses: ['Đỏ có Mã bảo vệ từ sớm nên phòng ngự rất êm thấm.'],
    grandmasters: ['Vương Thiên Nhất', 'Tưởng Xuyên'],
    stats: {
      redWinRate: 36,
      drawRate: 46,
      blackWinRate: 18,
      popularity: 76,
      totalGamesSample: 5400,
    },
    moves: [
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Khởi Mã.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen vào Trung Pháo.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Thất Binh.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã Đen lên.', isKeyMove: true },
      { from: 'b1', to: 'c3', notation: 'M8.7', commentary: 'Đỏ lên tiếp Mã 8 tiến 7 vững như bàn thạch.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe đối ứng.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen hoàn thiện trận hình.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 8. PHI TƯỢNG CUỘC
  // ==========================================
  {
    id: 'phi-tuong-cuoc-vs-ta-trung-phao',
    name: 'Phi Tượng Cuộc Đối Tả Trung Pháo',
    vietnameseName: 'Phi Tượng Cuộc Đối Tả Trung Pháo',
    chineseName: '飞相局对左中炮',
    category: 'phi-tuong',
    side: 'both',
    eco: 'E01',
    description: 'Đỏ nước đầu bay Tượng (Tượng 3 tiến 5 hoặc Tượng 7 tiến 5) lấy tĩnh chế động. Đen đáp trả bằng Tả Trung Pháo (Pháo 8 bình 5) tạo nên cuộc chiến kinh điển giữa tấm khiên thép và ngọn giáo nhọn.',
    strategicGoals: [
      'Đỏ củng cố trung lộ vững như bàn thạch, sau đó phát triển Xe Mã hai cánh phản kích.',
      'Đen dùng Pháo đầu cố gắng khoét sâu vào trung lộ Đỏ trước khi Đỏ hoàn thành thế trận.',
    ],
    strengths: ['Thế trận cực kỳ khó bị công phá, rất thích hợp cho lối đánh chắc chắn.'],
    weaknesses: ['Nhịp độ ván đấu diễn ra chậm rãi.'],
    grandmasters: ['Hồ Vinh Hoa', 'Hứa Ngân Xuyên', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 36,
      drawRate: 49,
      blackWinRate: 15,
      popularity: 89,
      totalGamesSample: 15300,
    },
    moves: [
      { from: 'g1', to: 'e3', notation: 'T7.5', commentary: 'Đỏ Phi Tượng (Tượng 7 tiến 5) gia cố trung lộ từ nước đầu.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen vào Tả Trung Pháo quyết công phá trung lộ.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã bảo vệ Tốt đầu.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã 8 tiến 7.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Thất Binh mở đường Mã.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã hoàn thành Bình Phong Pháo.', isKeyMove: true },
    ],
  },
  {
    id: 'phi-tuong-cuoc-vs-tien-tot',
    name: 'Phi Tượng Cuộc Đối Tiến Tốt (Đề Binh)',
    vietnameseName: 'Phi Tượng Cuộc Đối Tiến Tốt',
    chineseName: '飞相局对进卒',
    category: 'phi-tuong',
    side: 'both',
    eco: 'E02',
    description: 'Cả hai bên cùng phát triển quân hài hòa, không vội công kích mà so đọ chiều sâu chiến thuật trung tàn cuộc.',
    strategicGoals: ['Thiết lập thế trận cân bằng và chờ đợi đối phương mắc sai lầm.'],
    strengths: ['Tỷ lệ hòa rất cao, thế trận kín kẽ.'],
    weaknesses: ['Ít cơ hội thắng nhanh.'],
    grandmasters: ['Hứa Ngân Xuyên', 'Trịnh Duy Đồng'],
    stats: {
      redWinRate: 33,
      drawRate: 54,
      blackWinRate: 13,
      popularity: 82,
      totalGamesSample: 9100,
    },
    moves: [
      { from: 'g1', to: 'e3', notation: 'T7.5', commentary: 'Phi Tượng.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen tiến Tốt 7.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Mã 8 tiến 7.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Thúc Thất Binh.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Lên Mã đối xứng.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Xuất Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Xuất Xe.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 9. QUÁ CUNG PHÁO & SĨ GIÁC PHÁO
  // ==========================================
  {
    id: 'qua-cung-phao-vs-trung-phao',
    name: 'Quá Cung Pháo Đối Trung Pháo',
    vietnameseName: 'Quá Cung Pháo Đối Trung Pháo',
    chineseName: '过宫炮对中炮',
    category: 'qua-cung-si-giac',
    side: 'both',
    eco: 'Q01',
    description: 'Đỏ nước đầu đi Pháo 2 bình 6 (vượt qua cung Tướng sang cánh trái) để tập trung lực lượng công phá cánh yếu của Đen. Đen đáp trả bằng Trung Pháo vỗ mặt để lấy lại thế trận.',
    strategicGoals: [
      'Đỏ chuyển Pháo sang cánh nhằm tập trung hỏa lực 2 Pháo 1 Xe công phá một mạn sườn.',
      'Đen dùng Trung Pháo gây áp lực trung lộ khi Đỏ vừa di chuyển Pháo đi.',
    ],
    strengths: ['Lối đánh linh hoạt, khó lường, tạo đột biến cao.'],
    weaknesses: ['Hơi lỏng trung lộ ở vài nước đầu.'],
    grandmasters: ['Hồ Vinh Hoa', 'Triệu Hâm Hâm', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 36,
      drawRate: 44,
      blackWinRate: 20,
      popularity: 84,
      totalGamesSample: 8800,
    },
    moves: [
      { from: 'h3', to: 'd3', notation: 'P2-6', commentary: 'Đỏ khởi Quá Cung Pháo (Pháo 2 bình 6) tập trung hỏa lực cánh trái.', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen vào Trung Pháo khai thác trung lộ Đỏ.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã bảo vệ Tốt đầu.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã 8 tiến 7.', isKeyMove: true },
      { from: 'b1', to: 'c3', notation: 'M8.7', commentary: 'Đỏ nhảy tiếp Mã 8 tiến 7.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'a1', to: 'b1', notation: 'X9-8', commentary: 'Đỏ xuất Xe cánh trái.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen hoàn chỉnh trận hình.', isKeyMove: true },
    ],
  },
  {
    id: 'si-giac-phao-vs-trung-phao',
    name: 'Sĩ Giác Pháo Đối Trung Pháo',
    vietnameseName: 'Sĩ Giác Pháo Đối Trung Pháo',
    chineseName: '士角炮对中炮',
    category: 'qua-cung-si-giac',
    side: 'both',
    eco: 'Q02',
    description: 'Đỏ vào Pháo 2 bình 4 (nằm ngay góc Sĩ) vừa kiềm chế Mã đối phương vừa hỗ trợ phòng thủ trung lộ chặt chẽ.',
    strategicGoals: ['Khống chế đường phát triển của đối phương từ góc hiểm.'],
    strengths: ['Công thủ vẹn toàn, vị trí Pháo góc Sĩ rất đắc địa.'],
    weaknesses: ['Tốc độ xuất Xe hơi chậm hơn.'],
    grandmasters: ['Lữ Khâm', 'Hồ Vinh Hoa'],
    stats: {
      redWinRate: 35,
      drawRate: 46,
      blackWinRate: 19,
      popularity: 79,
      totalGamesSample: 6200,
    },
    moves: [
      { from: 'h3', to: 'f3', notation: 'P2-4', commentary: 'Đỏ vào Sĩ Giác Pháo (Pháo 2 bình 4).', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen vào Trung Pháo.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã giữ Tốt giữa.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã.', isKeyMove: true },
      { from: 'c4', to: 'c5', notation: 'C7.1', commentary: 'Đỏ thúc Thất Binh.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã.', isKeyMove: true },
    ],
  },

  // ==========================================
  // 10. CẠM BẪY KHAI CUỘC & KỲ TRẬN
  // ==========================================
  {
    id: 'quy-boi-phao-tran-phap',
    name: 'Quy Bối Pháo (Rùa Lưng Vàng - Kỳ Trận Bí Truyền)',
    vietnameseName: 'Quy Bối Pháo (Rùa Lưng Vàng)',
    chineseName: '龟背炮秘阵',
    category: 'cam-bay-ky-tran',
    side: 'black',
    eco: 'TR01',
    description: 'Trận pháp dị biệt do danh thủ Trần Tùng Thuận sáng tạo: Đen thoái Pháo về đáy cung (Pháo 8 thoái 1) rồi hoành Xe kẹp nách Pháo, tựa như con rùa rút đầu vào mai để bất ngờ phản đòn đoạt quân thắng ván.',
    strategicGoals: [
      'Gài bẫy khiến Đỏ chủ quan lao Xe quá hà.',
      'Dùng Pháo đáy chuyển cánh bất ngờ kẹp chết Xe hoặc đoạt quân chớp nhoáng.',
    ],
    strengths: ['Bẫy cực kỳ hiểm độc, khó hóa giải nếu đối thủ chưa từng gặp.'],
    weaknesses: ['Nếu Đỏ không dính bẫy mà từ từ siết vòng vây, Đen sẽ bị lép vế.'],
    grandmasters: ['Trần Tùng Thuận', 'Hồ Vinh Hoa'],
    stats: {
      redWinRate: 38,
      drawRate: 28,
      blackWinRate: 34,
      popularity: 86,
      totalGamesSample: 4900,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã phải.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã phải.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy Mã 8 tiến 7 mở đường đáy cung.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Trực Xe.', isKeyMove: true },
      { from: 'b8', to: 'b9', notation: 'P8.1', commentary: 'Đen thoái Pháo về đáy cung (Quy Bối Pháo bí trận).', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ vội vã xông Xe quá hà (rơi vào bẫy rùa rút đầu).', isKeyMove: true },
      { from: 'b9', to: 'd9', notation: 'P8-6', commentary: 'Đen chuyển Pháo sang lộ 6 kẹp nách bắt chết Xe Đỏ!', isKeyMove: true },
    ],
    trapsAndMistakes: [
      'Đỏ không nên tham ăn Tốt hoặc đè Mã sớm khi Pháo Đen chưa lộ diện.',
      'Cần đề phòng đòn Pháo đáy bắn xuyên sườn.',
    ],
  },
  {
    id: 'uyen-uong-phao-tran-phap',
    name: 'Uyên Ương Pháo (Đôi Pháo Liền Cánh)',
    vietnameseName: 'Uyên Ương Pháo',
    chineseName: '鸳鸯炮奇阵',
    category: 'cam-bay-ky-tran',
    side: 'black',
    eco: 'TR02',
    description: 'Đen dồn cả hai Pháo về cùng một cánh (như đôi uyên ương sát cánh), phối hợp chặt chẽ để phong tỏa và bắt chết Xe của đối phương.',
    strategicGoals: ['Khống chế toàn bộ một hành lang và giăng bẫy bắt Xe đối thủ.'],
    strengths: ['Khả năng bắt Xe rất cao nếu đối phương sơ sẩy.'],
    weaknesses: ['Bỏ trống cánh còn lại, dễ bị phản kích nếu không thắng nhanh.'],
    grandmasters: ['Dương Quan Lân'],
    stats: {
      redWinRate: 40,
      drawRate: 26,
      blackWinRate: 34,
      popularity: 80,
      totalGamesSample: 3800,
    },
    moves: [
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Trung Pháo.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Mã 2 tiến 3.', isKeyMove: true },
      { from: 'b10', to: 'a8', notation: 'M8.9', commentary: 'Đen nhảy Mã biên (Mã 8 tiến 9) chuẩn bị thế trận Uyên Ương.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe chiếm lộ 2.', isKeyMove: true },
      { from: 'h8', to: 'h9', notation: 'P2.1', commentary: 'Đen nhấc Pháo 2 tiến 1 chuẩn bị ghép cặp.', isKeyMove: true },
      { from: 'h1', to: 'h6', notation: 'X2.6', commentary: 'Đỏ tiến Xe qua sông đè ép.', isKeyMove: true },
      { from: 'h9', to: 'b9', notation: 'P2-8', commentary: 'Đen chuyển Pháo sang lộ 8 tạo cặp Uyên Ương Pháo khóa chặt Xe Đỏ!', isKeyMove: true },
    ],
  },
  {
    id: 'thiet-hoat-xa-thi-quan',
    name: 'Thiết Hoạt Xa (Thí Pháo Đoạt Tiên Thần Tốc)',
    vietnameseName: 'Thiết Hoạt Xa Thí Quân Đoạt Tiên',
    chineseName: '铁滑车弃子神速',
    category: 'cam-bay-ky-tran',
    side: 'red',
    eco: 'TR03',
    description: 'Khai cuộc cuồng bạo của Đỏ: Bỏ không quân Pháo hoặc Mã ngay từ nước đầu để kích hoạt Xe lao vút qua sông như cỗ xe bọc thép (Thiết Hoạt Xa), tạo thế tấn công sấm sét.',
    strategicGoals: ['Hy sinh quân nhẹ để đổi lấy tốc độ và thế tấn công áp đảo hoàn toàn.'],
    strengths: ['Cực kỳ bất ngờ, gây hoảng loạn tâm lý cho đối thủ.'],
    weaknesses: ['Thiệt quân thực chất, nếu đối phương bình tĩnh hóa giải sẽ thua cờ.'],
    grandmasters: ['Liễu Đại Hoa'],
    stats: {
      redWinRate: 42,
      drawRate: 15,
      blackWinRate: 43,
      popularity: 85,
      totalGamesSample: 4100,
    },
    moves: [
      { from: 'i1', to: 'i2', notation: 'X1.1', commentary: 'Đỏ khởi Hoành Xe ngay nước 1 (Thiết Hoạt Xa khai trận).', isKeyMove: true },
      { from: 'b8', to: 'e8', notation: 'P8-5', commentary: 'Đen vào Trung Pháo uy hiếp trung lộ.', isKeyMove: true },
      { from: 'i2', to: 'd2', notation: 'X1-4', commentary: 'Đỏ bình Xe sang lộ 4 tạo thế công sấm sét.', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen nhảy Mã 8 tiến 7 phòng ngự.', isKeyMove: true },
      { from: 'd2', to: 'd6', notation: 'X4.4', commentary: 'Đỏ thúc Xe xông thẳng qua sông chiếm lĩnh tuyến hiểm!', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã chống đỡ.', isKeyMove: true },
      { from: 'h3', to: 'e3', notation: 'P2-5', commentary: 'Đỏ tiếp tục vào Trung Pháo vỗ mặt đối công bão táp.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe đối kháng.', isKeyMove: true },
    ],
  },
  {
    id: 'dan-phuong-trieu-duong',
    name: 'Đan Phượng Triều Dương (Chim Phượng Hoàng Hướng Mặt Trời)',
    vietnameseName: 'Đan Phượng Triều Dương',
    chineseName: '丹凤朝阳',
    category: 'cam-bay-ky-tran',
    side: 'both',
    eco: 'TR04',
    description: 'Trận pháp hoa mỹ với nước Phi Tượng kết hợp nâng Pháo tuần hà bay bổng như phượng hoàng giương cánh đón bình minh.',
    strategicGoals: ['Tạo thế trận thẩm mỹ cao, chuyển thế linh hoạt từ tĩnh sang động.'],
    strengths: ['Hình cờ thanh thoát, khó bị bắt bài.'],
    weaknesses: ['Đòi hỏi kỳ thủ có trình độ trung cuộc tinh tế.'],
    grandmasters: ['Hồ Vinh Hoa', 'Lại Lý Huynh'],
    stats: {
      redWinRate: 37,
      drawRate: 45,
      blackWinRate: 18,
      popularity: 78,
      totalGamesSample: 3500,
    },
    moves: [
      { from: 'g1', to: 'e3', notation: 'T7.5', commentary: 'Đỏ Phi Tượng thanh tao.', isKeyMove: true },
      { from: 'c7', to: 'c6', notation: 'B7.1', commentary: 'Đen tiến Tốt 7.', isKeyMove: true },
      { from: 'h3', to: 'h5', notation: 'P2.4', commentary: 'Đỏ nâng Pháo tuần hà như Phượng Hoàng cất cánh!', isKeyMove: true },
      { from: 'b10', to: 'c8', notation: 'M8.7', commentary: 'Đen lên Mã.', isKeyMove: true },
      { from: 'h1', to: 'g3', notation: 'M2.3', commentary: 'Đỏ lên Mã giữ trận.', isKeyMove: true },
      { from: 'h10', to: 'g8', notation: 'M2.3', commentary: 'Đen lên Mã đối xứng.', isKeyMove: true },
      { from: 'i1', to: 'h1', notation: 'X1-2', commentary: 'Đỏ xuất Xe.', isKeyMove: true },
      { from: 'a10', to: 'b10', notation: 'X9-8', commentary: 'Đen xuất Xe.', isKeyMove: true },
    ],
  },
];
